package com.el.mbg.mapper;

import com.el.mbg.domain.TB2bSo;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface TB2bSoMapper {
    @Delete({
        "delete from B2B_SO",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Long id);

    @Insert({
        "insert into B2B_SO ( ",
//        "ID, " +
//            "TENANT_ID, ",
        "OU_ID, ORG_ID, DOC_NO, ",
        "DOC_TYPE, DOC_STATUS, ",
        "DOC_TIME, SO_BATCH_ID, ",
        "DOC_NO2, DOC_TYPE2, ",
        "SO_SOURCE, SALE_REGION, ",
        "DELIVER_REGION, CUST_ID, ",
        "CUST_CODE, SO_EMP_ID, ",
        "AGENT_EMP_ID, CURR_CODE, ",
        "TAX_CODE, APPR_STATUS, ",
        "APPR_TIME, APPR_USER_ID, ",
        "PAY_STATUS, PAY_TIME, ",
        "PAY_TRANS_ID, PAY_METHOD, ",
        "PAYMENT_TERM, PL_DATE, ",
        "DELIVER_STATUS, DELIVER_WAY, ",
        "DELIVER_CONTACT, DELIVER_ADDRESS_ID, ",
        "DELIVER_ADDRESS, SHIP_TIME, ",
        "DELIVER_TIME, RECEIVE_TIME, ",
        "RETURN_STATUS, RETURN_APPLY_TIME, ",
        "RETURN_APPR_TIME, COMMENT_STATUS, ",
        "COMMENT_TYPE, COMMENT_TIME, ",
        "COMMENT_CONTENT, CANCEL_TIME, ",
        "CANCEL_REASON, REFUND_STATUS, ",
        "REFUND_TIME, REFUND_AMT, ",
        "DISC_AMT, TAX_RATE, ",
        "TAX_AMT, NET_AMT, ",
        "FREIGHT_FEE, AMT, ",
        "TSO_ID, REMARK, OUTER_CODE, ",
//        "CREATE_USER_ID, CREATE_TIME, ",
//        "MODIFY_USER_ID, MODIFY_TIME, ",
        "AUDIT_DATA_VERSION, DELETE_FLAG, MOBILE, DELIVER_ADDRESS_NO, OU_CODE)",
        "values ( ",
//        "#{id,jdbcType=DECIMAL}, " ,
//            " #{tenantId,jdbcType=DECIMAL}, ",
        "#{ouId,jdbcType=DECIMAL}, #{orgId,jdbcType=DECIMAL}, #{docNo,jdbcType=VARCHAR}, ",
        "#{docType,jdbcType=VARCHAR}, #{docStatus,jdbcType=VARCHAR}, ",
        "#{docTime,jdbcType=TIMESTAMP}, #{soBatchId,jdbcType=DECIMAL}, ",
        "#{docNo2,jdbcType=VARCHAR}, #{docType2,jdbcType=VARCHAR}, ",
        "#{soSource,jdbcType=VARCHAR}, #{saleRegion,jdbcType=VARCHAR}, ",
        "#{deliverRegion,jdbcType=VARCHAR}, #{custId,jdbcType=DECIMAL}, ",
        "#{custCode,jdbcType=VARCHAR}, #{soEmpId,jdbcType=DECIMAL}, ",
        "#{agentEmpId,jdbcType=DECIMAL}, #{currCode,jdbcType=VARCHAR}, ",
        "#{taxCode,jdbcType=VARCHAR}, #{apprStatus,jdbcType=VARCHAR}, ",
        "#{apprTime,jdbcType=TIMESTAMP}, #{apprUserId,jdbcType=DECIMAL}, ",
        "#{payStatus,jdbcType=VARCHAR}, #{payTime,jdbcType=TIMESTAMP}, ",
        "#{payTransId,jdbcType=DECIMAL}, #{payMethod,jdbcType=VARCHAR}, ",
        "#{paymentTerm,jdbcType=VARCHAR}, #{plDate,jdbcType=TIMESTAMP}, ",
        "#{deliverStatus,jdbcType=VARCHAR}, #{deliverWay,jdbcType=VARCHAR}, ",
        "#{deliverContact,jdbcType=VARCHAR}, #{deliverAddressId,jdbcType=DECIMAL}, ",
        "#{deliverAddress,jdbcType=VARCHAR}, #{shipTime,jdbcType=TIMESTAMP}, ",
        "#{deliverTime,jdbcType=TIMESTAMP}, #{receiveTime,jdbcType=TIMESTAMP}, ",
        "#{returnStatus,jdbcType=VARCHAR}, #{returnApplyTime,jdbcType=TIMESTAMP}, ",
        "#{returnApprTime,jdbcType=TIMESTAMP}, #{commentStatus,jdbcType=VARCHAR}, ",
        "#{commentType,jdbcType=VARCHAR}, #{commentTime,jdbcType=TIMESTAMP}, ",
        "#{commentContent,jdbcType=VARCHAR}, #{cancelTime,jdbcType=TIMESTAMP}, ",
        "#{cancelReason,jdbcType=VARCHAR}, #{refundStatus,jdbcType=VARCHAR}, ",
        "#{refundTime,jdbcType=TIMESTAMP}, #{refundAmt,jdbcType=DECIMAL}, ",
        "#{discAmt,jdbcType=DECIMAL}, #{taxRate,jdbcType=DECIMAL}, ",
        "#{taxAmt,jdbcType=DECIMAL}, #{netAmt,jdbcType=DECIMAL}, ",
        "#{freightFee,jdbcType=DECIMAL}, #{amt,jdbcType=DECIMAL}, ",
        "#{tsoId,jdbcType=DECIMAL}, #{remark,jdbcType=VARCHAR}, #{outerCode,jdbcType=VARCHAR}, ",
//        "#{createUserId,jdbcType=DECIMAL}, #{createTime,jdbcType=TIMESTAMP}, ",
//        "#{modifyUserId,jdbcType=DECIMAL}, #{modifyTime,jdbcType=TIMESTAMP}, ",
        "#{auditDataVersion,jdbcType=DECIMAL}, #{deleteFlag,jdbcType=DECIMAL}, ",
        "#{mobile,jdbcType=VARCHAR}, #{deliverAddressNo,jdbcType=VARCHAR}, ",
        " #{ouCode,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID() AS id FROM DUAL", keyProperty="id", before=false, resultType=Long.class)
    int insert(TB2bSo record);

    @Select({
        "select",
        "ID, TENANT_ID, OU_ID, ORG_ID, DOC_NO, DOC_TYPE, DOC_STATUS, DOC_TIME, SO_BATCH_ID, ",
        "DOC_NO2, DOC_TYPE2, SO_SOURCE, SALE_REGION, DELIVER_REGION, CUST_ID, CUST_CODE, ",
        "SO_EMP_ID, AGENT_EMP_ID, CURR_CODE, TAX_CODE, APPR_STATUS, APPR_TIME, APPR_USER_ID, ",
        "PAY_STATUS, PAY_TIME, PAY_TRANS_ID, PAY_METHOD, PAYMENT_TERM, PL_DATE, DELIVER_STATUS, ",
        "DELIVER_WAY, DELIVER_CONTACT, DELIVER_ADDRESS_ID, DELIVER_ADDRESS, SHIP_TIME, ",
        "DELIVER_TIME, RECEIVE_TIME, RETURN_STATUS, RETURN_APPLY_TIME, RETURN_APPR_TIME, ",
        "COMMENT_STATUS, COMMENT_TYPE, COMMENT_TIME, COMMENT_CONTENT, CANCEL_TIME, CANCEL_REASON, ",
        "REFUND_STATUS, REFUND_TIME, REFUND_AMT, DISC_AMT, TAX_RATE, TAX_AMT, NET_AMT, ",
        "FREIGHT_FEE, AMT, TSO_ID, REMARK, OUTER_CODE, CREATE_USER_ID, CREATE_TIME, MODIFY_USER_ID, ",
        "MODIFY_TIME, AUDIT_DATA_VERSION, DELETE_FLAG",
        "from B2B_SO",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="TENANT_ID", property="tenantId", jdbcType=JdbcType.DECIMAL),
        @Result(column="OU_ID", property="ouId", jdbcType=JdbcType.DECIMAL),
        @Result(column="ORG_ID", property="orgId", jdbcType=JdbcType.DECIMAL),
        @Result(column="DOC_NO", property="docNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="DOC_TYPE", property="docType", jdbcType=JdbcType.VARCHAR),
        @Result(column="DOC_STATUS", property="docStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="DOC_TIME", property="docTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="SO_BATCH_ID", property="soBatchId", jdbcType=JdbcType.DECIMAL),
        @Result(column="DOC_NO2", property="docNo2", jdbcType=JdbcType.VARCHAR),
        @Result(column="DOC_TYPE2", property="docType2", jdbcType=JdbcType.VARCHAR),
        @Result(column="SO_SOURCE", property="soSource", jdbcType=JdbcType.VARCHAR),
        @Result(column="SALE_REGION", property="saleRegion", jdbcType=JdbcType.VARCHAR),
        @Result(column="DELIVER_REGION", property="deliverRegion", jdbcType=JdbcType.VARCHAR),
        @Result(column="CUST_ID", property="custId", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUST_CODE", property="custCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="SO_EMP_ID", property="soEmpId", jdbcType=JdbcType.DECIMAL),
        @Result(column="AGENT_EMP_ID", property="agentEmpId", jdbcType=JdbcType.DECIMAL),
        @Result(column="CURR_CODE", property="currCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="TAX_CODE", property="taxCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="APPR_STATUS", property="apprStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="APPR_TIME", property="apprTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="APPR_USER_ID", property="apprUserId", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAY_STATUS", property="payStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="PAY_TIME", property="payTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="PAY_TRANS_ID", property="payTransId", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAY_METHOD", property="payMethod", jdbcType=JdbcType.VARCHAR),
        @Result(column="PAYMENT_TERM", property="paymentTerm", jdbcType=JdbcType.VARCHAR),
        @Result(column="PL_DATE", property="plDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DELIVER_STATUS", property="deliverStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="DELIVER_WAY", property="deliverWay", jdbcType=JdbcType.VARCHAR),
        @Result(column="DELIVER_CONTACT", property="deliverContact", jdbcType=JdbcType.VARCHAR),
        @Result(column="DELIVER_ADDRESS_ID", property="deliverAddressId", jdbcType=JdbcType.DECIMAL),
        @Result(column="DELIVER_ADDRESS", property="deliverAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="SHIP_TIME", property="shipTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DELIVER_TIME", property="deliverTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="RECEIVE_TIME", property="receiveTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="RETURN_STATUS", property="returnStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="RETURN_APPLY_TIME", property="returnApplyTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="RETURN_APPR_TIME", property="returnApprTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="COMMENT_STATUS", property="commentStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="COMMENT_TYPE", property="commentType", jdbcType=JdbcType.VARCHAR),
        @Result(column="COMMENT_TIME", property="commentTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="COMMENT_CONTENT", property="commentContent", jdbcType=JdbcType.VARCHAR),
        @Result(column="CANCEL_TIME", property="cancelTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CANCEL_REASON", property="cancelReason", jdbcType=JdbcType.VARCHAR),
        @Result(column="REFUND_STATUS", property="refundStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="REFUND_TIME", property="refundTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="REFUND_AMT", property="refundAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="DISC_AMT", property="discAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="TAX_RATE", property="taxRate", jdbcType=JdbcType.DECIMAL),
        @Result(column="TAX_AMT", property="taxAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="NET_AMT", property="netAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREIGHT_FEE", property="freightFee", jdbcType=JdbcType.DECIMAL),
        @Result(column="AMT", property="amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="TSO_ID", property="tsoId", jdbcType=JdbcType.DECIMAL),
        @Result(column="REMARK", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="OUTER_CODE", property="outerCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_USER_ID", property="createUserId", jdbcType=JdbcType.DECIMAL),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFY_USER_ID", property="modifyUserId", jdbcType=JdbcType.DECIMAL),
        @Result(column="MODIFY_TIME", property="modifyTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="AUDIT_DATA_VERSION", property="auditDataVersion", jdbcType=JdbcType.DECIMAL),
        @Result(column="DELETE_FLAG", property="deleteFlag", jdbcType=JdbcType.DECIMAL)
    })
    TB2bSo selectByPrimaryKey(Long id);

    @Select({
        "select",
        "ID, TENANT_ID, OU_ID, ORG_ID, DOC_NO, DOC_TYPE, DOC_STATUS, DOC_TIME, SO_BATCH_ID, ",
        "DOC_NO2, DOC_TYPE2, SO_SOURCE, SALE_REGION, DELIVER_REGION, CUST_ID, CUST_CODE, ",
        "SO_EMP_ID, AGENT_EMP_ID, CURR_CODE, TAX_CODE, APPR_STATUS, APPR_TIME, APPR_USER_ID, ",
        "PAY_STATUS, PAY_TIME, PAY_TRANS_ID, PAY_METHOD, PAYMENT_TERM, PL_DATE, DELIVER_STATUS, ",
        "DELIVER_WAY, DELIVER_CONTACT, DELIVER_ADDRESS_ID, DELIVER_ADDRESS, SHIP_TIME, ",
        "DELIVER_TIME, RECEIVE_TIME, RETURN_STATUS, RETURN_APPLY_TIME, RETURN_APPR_TIME, ",
        "COMMENT_STATUS, COMMENT_TYPE, COMMENT_TIME, COMMENT_CONTENT, CANCEL_TIME, CANCEL_REASON, ",
        "REFUND_STATUS, REFUND_TIME, REFUND_AMT, DISC_AMT, TAX_RATE, TAX_AMT, NET_AMT, ",
        "FREIGHT_FEE, AMT, TSO_ID, REMARK, OUTER_CODE, CREATE_USER_ID, CREATE_TIME, MODIFY_USER_ID, ",
        "MODIFY_TIME, AUDIT_DATA_VERSION, DELETE_FLAG",
        "from B2B_SO"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="TENANT_ID", property="tenantId", jdbcType=JdbcType.DECIMAL),
        @Result(column="OU_ID", property="ouId", jdbcType=JdbcType.DECIMAL),
        @Result(column="ORG_ID", property="orgId", jdbcType=JdbcType.DECIMAL),
        @Result(column="DOC_NO", property="docNo", jdbcType=JdbcType.VARCHAR),
        @Result(column="DOC_TYPE", property="docType", jdbcType=JdbcType.VARCHAR),
        @Result(column="DOC_STATUS", property="docStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="DOC_TIME", property="docTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="SO_BATCH_ID", property="soBatchId", jdbcType=JdbcType.DECIMAL),
        @Result(column="DOC_NO2", property="docNo2", jdbcType=JdbcType.VARCHAR),
        @Result(column="DOC_TYPE2", property="docType2", jdbcType=JdbcType.VARCHAR),
        @Result(column="SO_SOURCE", property="soSource", jdbcType=JdbcType.VARCHAR),
        @Result(column="SALE_REGION", property="saleRegion", jdbcType=JdbcType.VARCHAR),
        @Result(column="DELIVER_REGION", property="deliverRegion", jdbcType=JdbcType.VARCHAR),
        @Result(column="CUST_ID", property="custId", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUST_CODE", property="custCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="SO_EMP_ID", property="soEmpId", jdbcType=JdbcType.DECIMAL),
        @Result(column="AGENT_EMP_ID", property="agentEmpId", jdbcType=JdbcType.DECIMAL),
        @Result(column="CURR_CODE", property="currCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="TAX_CODE", property="taxCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="APPR_STATUS", property="apprStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="APPR_TIME", property="apprTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="APPR_USER_ID", property="apprUserId", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAY_STATUS", property="payStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="PAY_TIME", property="payTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="PAY_TRANS_ID", property="payTransId", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAY_METHOD", property="payMethod", jdbcType=JdbcType.VARCHAR),
        @Result(column="PAYMENT_TERM", property="paymentTerm", jdbcType=JdbcType.VARCHAR),
        @Result(column="PL_DATE", property="plDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DELIVER_STATUS", property="deliverStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="DELIVER_WAY", property="deliverWay", jdbcType=JdbcType.VARCHAR),
        @Result(column="DELIVER_CONTACT", property="deliverContact", jdbcType=JdbcType.VARCHAR),
        @Result(column="DELIVER_ADDRESS_ID", property="deliverAddressId", jdbcType=JdbcType.DECIMAL),
        @Result(column="DELIVER_ADDRESS", property="deliverAddress", jdbcType=JdbcType.VARCHAR),
        @Result(column="SHIP_TIME", property="shipTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="DELIVER_TIME", property="deliverTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="RECEIVE_TIME", property="receiveTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="RETURN_STATUS", property="returnStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="RETURN_APPLY_TIME", property="returnApplyTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="RETURN_APPR_TIME", property="returnApprTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="COMMENT_STATUS", property="commentStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="COMMENT_TYPE", property="commentType", jdbcType=JdbcType.VARCHAR),
        @Result(column="COMMENT_TIME", property="commentTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="COMMENT_CONTENT", property="commentContent", jdbcType=JdbcType.VARCHAR),
        @Result(column="CANCEL_TIME", property="cancelTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="CANCEL_REASON", property="cancelReason", jdbcType=JdbcType.VARCHAR),
        @Result(column="REFUND_STATUS", property="refundStatus", jdbcType=JdbcType.VARCHAR),
        @Result(column="REFUND_TIME", property="refundTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="REFUND_AMT", property="refundAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="DISC_AMT", property="discAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="TAX_RATE", property="taxRate", jdbcType=JdbcType.DECIMAL),
        @Result(column="TAX_AMT", property="taxAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="NET_AMT", property="netAmt", jdbcType=JdbcType.DECIMAL),
        @Result(column="FREIGHT_FEE", property="freightFee", jdbcType=JdbcType.DECIMAL),
        @Result(column="AMT", property="amt", jdbcType=JdbcType.DECIMAL),
        @Result(column="TSO_ID", property="tsoId", jdbcType=JdbcType.DECIMAL),
        @Result(column="REMARK", property="remark", jdbcType=JdbcType.VARCHAR),
        @Result(column="OUTER_CODE", property="outerCode", jdbcType=JdbcType.VARCHAR),
        @Result(column="CREATE_USER_ID", property="createUserId", jdbcType=JdbcType.DECIMAL),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFY_USER_ID", property="modifyUserId", jdbcType=JdbcType.DECIMAL),
        @Result(column="MODIFY_TIME", property="modifyTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="AUDIT_DATA_VERSION", property="auditDataVersion", jdbcType=JdbcType.DECIMAL),
        @Result(column="DELETE_FLAG", property="deleteFlag", jdbcType=JdbcType.DECIMAL)
    })
    List<TB2bSo> selectAll();

    @Update({
        "update B2B_SO",
        "set ",
//          "TENANT_ID = #{tenantId,jdbcType=DECIMAL},",
//          "OU_ID = #{ouId,jdbcType=DECIMAL},",
//          "ORG_ID = #{orgId,jdbcType=DECIMAL},",
//          "DOC_NO = #{docNo,jdbcType=VARCHAR},",
//          "DOC_TYPE = #{docType,jdbcType=VARCHAR},",
          "DOC_STATUS = #{docStatus,jdbcType=VARCHAR},",
          "DOC_TIME = #{docTime,jdbcType=TIMESTAMP},",
//          "SO_BATCH_ID = #{soBatchId,jdbcType=DECIMAL},",
//          "DOC_NO2 = #{docNo2,jdbcType=VARCHAR},",
//          "DOC_TYPE2 = #{docType2,jdbcType=VARCHAR},",
//          "SO_SOURCE = #{soSource,jdbcType=VARCHAR},",
//          "SALE_REGION = #{saleRegion,jdbcType=VARCHAR},",
//          "DELIVER_REGION = #{deliverRegion,jdbcType=VARCHAR},",
//          "CUST_ID = #{custId,jdbcType=DECIMAL},",
//          "CUST_CODE = #{custCode,jdbcType=VARCHAR},",
//          "SO_EMP_ID = #{soEmpId,jdbcType=DECIMAL},",
//          "AGENT_EMP_ID = #{agentEmpId,jdbcType=DECIMAL},",
//          "CURR_CODE = #{currCode,jdbcType=VARCHAR},",
//          "TAX_CODE = #{taxCode,jdbcType=VARCHAR},",
//          "APPR_STATUS = #{apprStatus,jdbcType=VARCHAR},",
//          "APPR_TIME = #{apprTime,jdbcType=TIMESTAMP},",
//          "APPR_USER_ID = #{apprUserId,jdbcType=DECIMAL},",
//          "PAY_STATUS = #{payStatus,jdbcType=VARCHAR},",
//          "PAY_TIME = #{payTime,jdbcType=TIMESTAMP},",
//          "PAY_TRANS_ID = #{payTransId,jdbcType=DECIMAL},",
//          "PAY_METHOD = #{payMethod,jdbcType=VARCHAR},",
//          "PAYMENT_TERM = #{paymentTerm,jdbcType=VARCHAR},",
//          "PL_DATE = #{plDate,jdbcType=TIMESTAMP},",
//          "DELIVER_STATUS = #{deliverStatus,jdbcType=VARCHAR},",
          "DELIVER_WAY = #{deliverWay,jdbcType=VARCHAR},",
          "DELIVER_CONTACT = #{deliverContact,jdbcType=VARCHAR},",
          "DELIVER_ADDRESS_ID = #{deliverAddressId,jdbcType=DECIMAL},",
          "DELIVER_ADDRESS = #{deliverAddress,jdbcType=VARCHAR},",
//          "SHIP_TIME = #{shipTime,jdbcType=TIMESTAMP},",
//          "DELIVER_TIME = #{deliverTime,jdbcType=TIMESTAMP},",
//          "RECEIVE_TIME = #{receiveTime,jdbcType=TIMESTAMP},",
//          "RETURN_STATUS = #{returnStatus,jdbcType=VARCHAR},",
//          "RETURN_APPLY_TIME = #{returnApplyTime,jdbcType=TIMESTAMP},",
//          "RETURN_APPR_TIME = #{returnApprTime,jdbcType=TIMESTAMP},",
//          "COMMENT_STATUS = #{commentStatus,jdbcType=VARCHAR},",
//          "COMMENT_TYPE = #{commentType,jdbcType=VARCHAR},",
//          "COMMENT_TIME = #{commentTime,jdbcType=TIMESTAMP},",
//          "COMMENT_CONTENT = #{commentContent,jdbcType=VARCHAR},",
//          "CANCEL_TIME = #{cancelTime,jdbcType=TIMESTAMP},",
//          "CANCEL_REASON = #{cancelReason,jdbcType=VARCHAR},",
//          "REFUND_STATUS = #{refundStatus,jdbcType=VARCHAR},",
//          "REFUND_TIME = #{refundTime,jdbcType=TIMESTAMP},",
//          "REFUND_AMT = #{refundAmt,jdbcType=DECIMAL},",
//          "DISC_AMT = #{discAmt,jdbcType=DECIMAL},",
//          "TAX_RATE = #{taxRate,jdbcType=DECIMAL},",
//          "TAX_AMT = #{taxAmt,jdbcType=DECIMAL},",
//          "NET_AMT = #{netAmt,jdbcType=DECIMAL},",
//          "FREIGHT_FEE = #{freightFee,jdbcType=DECIMAL},",
//          "AMT = #{amt,jdbcType=DECIMAL},",
//          "TSO_ID = #{tsoId,jdbcType=DECIMAL},",
          "REMARK = #{remark,jdbcType=VARCHAR},",
//          "OUTER_CODE = #{outerCode,jdbcType=VARCHAR},",
//          "CREATE_USER_ID = #{createUserId,jdbcType=DECIMAL},",
//          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
//          "MODIFY_USER_ID = #{modifyUserId,jdbcType=DECIMAL},",
          "MODIFY_TIME = #{modifyTime,jdbcType=TIMESTAMP},",
//          "AUDIT_DATA_VERSION = #{auditDataVersion,jdbcType=DECIMAL},",
          "MOBILE=#{mobile,jdbcType=VARCHAR},",
          "DELIVER_ADDRESS_NO=#{deliverAddressNo,jdbcType=VARCHAR},",
          "DELETE_FLAG = #{deleteFlag,jdbcType=DECIMAL},",
          "TRANSFER_FLAG=#{transferFlag,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(TB2bSo record);

    @Update({
        "update B2B_SO",
        "set DELETE_FLAG = 1",
        "where ID = #{id,jdbcType=DECIMAL} and DOC_STATUS = 'ORDERED'"
    })
    int deleteBySoId(long soId);
}
