package com.el.mbg.mapper;

import com.el.mbg.domain.TPbCust;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface TPbCustMapper {
    @Delete({
        "delete from PB_CUST",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Long id);

    @Insert({
        "insert into PB_CUST (ID, TENANT_ID, ",
        "OU_ID, ORG_ID, CUST_CODE, ",
        "CUST_NAME, CUST_ABBR, ",
        "CUST_TYPE, CUST_STATUS, ",
        "PID, ADDR_NO, PINYIN, ",
        "PINYIN_SH, COMP_CAPITAL, ",
        "AGENT_EMP_ID, CUST_CURR, ",
        "CREDIT_LIMIT, CREDIT_BAL, ",
        "PAYMENT_TERM, SETTLE_TYPE, ",
        "RECON_PERIOD, SETTLE_MONTHLY_DAY, ",
        "DEF_ORG_ID, DEF_WH_ID, ",
        "C1, C2, C3, ",
        "COUNTRY, POSTCODE, ",
        "REGION, CUST_LEVEL, ",
        "CUST_GROUP, VIP_NO, ",
        "VIP_LEVEL, VIP_GROUP, ",
        "CUST_POINT_FLAG, POINT, ",
        "CUST_SOURCE, VALID_FROM, ",
        "VALID_TO, INV_TYPE, ",
        "INV_TITLE, INV_TAXNO, ",
        "TAX_CODE, IC_REGISTER_NO, ",
        "REGISTER_DATE, REGISTER_ADDRESS, ",
        "REGISTER_TRADEMARK_NO, REGISTER_FUND, ",
        "REGISTER_FUND_CURRY, REPR, ",
        "COMP_NAME, COMP_PROP, ",
        "COMP_SCALE, COMP_BUSSADDR, ",
        "COMP_MAINBUSS, COMP_BUSSRANGE, ",
        "REMARK, OUTER_CODE, ",
        "CREATE_USER_ID, CREATE_TIME, ",
        "MODIFY_USER_ID, MODIFY_TIME, ",
        "AUDIT_DATA_VERSION, DELETE_FLAG, ",
        "PAY_METHOD, TAXPAYER_TYPE, ",
        "OU_CODE)",
        "values (#{id,jdbcType=DECIMAL}, #{tenantId,jdbcType=DECIMAL}, ",
        "#{ouId,jdbcType=DECIMAL}, #{orgId,jdbcType=DECIMAL}, #{custCode,jdbcType=NVARCHAR}, ",
        "#{custName,jdbcType=NVARCHAR}, #{custAbbr,jdbcType=NVARCHAR}, ",
        "#{custType,jdbcType=NVARCHAR}, #{custStatus,jdbcType=NVARCHAR}, ",
        "#{pid,jdbcType=DECIMAL}, #{addrNo,jdbcType=DECIMAL}, #{pinyin,jdbcType=NVARCHAR}, ",
        "#{pinyinSh,jdbcType=NVARCHAR}, #{compCapital,jdbcType=NVARCHAR}, ",
        "#{agentEmpId,jdbcType=DECIMAL}, #{custCurr,jdbcType=NVARCHAR}, ",
        "#{creditLimit,jdbcType=DECIMAL}, #{creditBal,jdbcType=DECIMAL}, ",
        "#{paymentTerm,jdbcType=NVARCHAR}, #{settleType,jdbcType=NVARCHAR}, ",
        "#{reconPeriod,jdbcType=NVARCHAR}, #{settleMonthlyDay,jdbcType=DECIMAL}, ",
        "#{defOrgId,jdbcType=DECIMAL}, #{defWhId,jdbcType=DECIMAL}, ",
        "#{c1,jdbcType=NVARCHAR}, #{c2,jdbcType=NVARCHAR}, #{c3,jdbcType=NVARCHAR}, ",
        "#{country,jdbcType=NVARCHAR}, #{postcode,jdbcType=NVARCHAR}, ",
        "#{region,jdbcType=NVARCHAR}, #{custLevel,jdbcType=NVARCHAR}, ",
        "#{custGroup,jdbcType=NVARCHAR}, #{vipNo,jdbcType=NVARCHAR}, ",
        "#{vipLevel,jdbcType=NVARCHAR}, #{vipGroup,jdbcType=NVARCHAR}, ",
        "#{custPointFlag,jdbcType=DECIMAL}, #{point,jdbcType=DECIMAL}, ",
        "#{custSource,jdbcType=NVARCHAR}, #{validFrom,jdbcType=TIMESTAMP}, ",
        "#{validTo,jdbcType=TIMESTAMP}, #{invType,jdbcType=NVARCHAR}, ",
        "#{invTitle,jdbcType=NVARCHAR}, #{invTaxno,jdbcType=NVARCHAR}, ",
        "#{taxCode,jdbcType=NVARCHAR}, #{icRegisterNo,jdbcType=NVARCHAR}, ",
        "#{registerDate,jdbcType=TIMESTAMP}, #{registerAddress,jdbcType=NVARCHAR}, ",
        "#{registerTrademarkNo,jdbcType=NVARCHAR}, #{registerFund,jdbcType=NVARCHAR}, ",
        "#{registerFundCurry,jdbcType=NVARCHAR}, #{repr,jdbcType=NVARCHAR}, ",
        "#{compName,jdbcType=NVARCHAR}, #{compProp,jdbcType=NVARCHAR}, ",
        "#{compScale,jdbcType=NVARCHAR}, #{compBussaddr,jdbcType=NVARCHAR}, ",
        "#{compMainbuss,jdbcType=NVARCHAR}, #{compBussrange,jdbcType=NVARCHAR}, ",
        "#{remark,jdbcType=NVARCHAR}, #{outerCode,jdbcType=NVARCHAR}, ",
        "#{createUserId,jdbcType=DECIMAL}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{modifyUserId,jdbcType=DECIMAL}, #{modifyTime,jdbcType=TIMESTAMP}, ",
        "#{auditDataVersion,jdbcType=DECIMAL}, #{deleteFlag,jdbcType=DECIMAL}, ",
        "#{payMethod,jdbcType=NVARCHAR}, #{taxpayerType,jdbcType=NVARCHAR}, ",
        "#{ouCode,jdbcType=NVARCHAR})"
    })
    @SelectKey(statement="SELECT SEQ_PB_CUST.NEXTVAL FROM DUAL", keyProperty="id", before=true, resultType=Long.class)
    int insert(TPbCust record);

    @Select({
        "select",
        "ID, TENANT_ID, OU_ID, ORG_ID, CUST_CODE, CUST_NAME, CUST_ABBR, CUST_TYPE, CUST_STATUS, ",
        "PID, ADDR_NO, PINYIN, PINYIN_SH, COMP_CAPITAL, AGENT_EMP_ID, CUST_CURR, CREDIT_LIMIT, ",
        "CREDIT_BAL, PAYMENT_TERM, SETTLE_TYPE, RECON_PERIOD, SETTLE_MONTHLY_DAY, DEF_ORG_ID, ",
        "DEF_WH_ID, C1, C2, C3, COUNTRY, POSTCODE, REGION, CUST_LEVEL, CUST_GROUP, VIP_NO, ",
        "VIP_LEVEL, VIP_GROUP, CUST_POINT_FLAG, POINT, CUST_SOURCE, VALID_FROM, VALID_TO, ",
        "INV_TYPE, INV_TITLE, INV_TAXNO, TAX_CODE, IC_REGISTER_NO, REGISTER_DATE, REGISTER_ADDRESS, ",
        "REGISTER_TRADEMARK_NO, REGISTER_FUND, REGISTER_FUND_CURRY, REPR, COMP_NAME, ",
        "COMP_PROP, COMP_SCALE, COMP_BUSSADDR, COMP_MAINBUSS, COMP_BUSSRANGE, REMARK, ",
        "OUTER_CODE, CREATE_USER_ID, CREATE_TIME, MODIFY_USER_ID, MODIFY_TIME, AUDIT_DATA_VERSION, ",
        "DELETE_FLAG, PAY_METHOD, TAXPAYER_TYPE, OU_CODE",
        "from PB_CUST",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="TENANT_ID", property="tenantId", jdbcType=JdbcType.DECIMAL),
        @Result(column="OU_ID", property="ouId", jdbcType=JdbcType.DECIMAL),
        @Result(column="ORG_ID", property="orgId", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUST_CODE", property="custCode", jdbcType=JdbcType.NVARCHAR),
        @Result(column="CUST_NAME", property="custName", jdbcType=JdbcType.NVARCHAR),
        @Result(column="CUST_ABBR", property="custAbbr", jdbcType=JdbcType.NVARCHAR),
        @Result(column="CUST_TYPE", property="custType", jdbcType=JdbcType.NVARCHAR),
        @Result(column="CUST_STATUS", property="custStatus", jdbcType=JdbcType.NVARCHAR),
        @Result(column="PID", property="pid", jdbcType=JdbcType.DECIMAL),
        @Result(column="ADDR_NO", property="addrNo", jdbcType=JdbcType.DECIMAL),
        @Result(column="PINYIN", property="pinyin", jdbcType=JdbcType.NVARCHAR),
        @Result(column="PINYIN_SH", property="pinyinSh", jdbcType=JdbcType.NVARCHAR),
        @Result(column="COMP_CAPITAL", property="compCapital", jdbcType=JdbcType.NVARCHAR),
        @Result(column="AGENT_EMP_ID", property="agentEmpId", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUST_CURR", property="custCurr", jdbcType=JdbcType.NVARCHAR),
        @Result(column="CREDIT_LIMIT", property="creditLimit", jdbcType=JdbcType.DECIMAL),
        @Result(column="CREDIT_BAL", property="creditBal", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAYMENT_TERM", property="paymentTerm", jdbcType=JdbcType.NVARCHAR),
        @Result(column="SETTLE_TYPE", property="settleType", jdbcType=JdbcType.NVARCHAR),
        @Result(column="RECON_PERIOD", property="reconPeriod", jdbcType=JdbcType.NVARCHAR),
        @Result(column="SETTLE_MONTHLY_DAY", property="settleMonthlyDay", jdbcType=JdbcType.DECIMAL),
        @Result(column="DEF_ORG_ID", property="defOrgId", jdbcType=JdbcType.DECIMAL),
        @Result(column="DEF_WH_ID", property="defWhId", jdbcType=JdbcType.DECIMAL),
        @Result(column="C1", property="c1", jdbcType=JdbcType.NVARCHAR),
        @Result(column="C2", property="c2", jdbcType=JdbcType.NVARCHAR),
        @Result(column="C3", property="c3", jdbcType=JdbcType.NVARCHAR),
        @Result(column="COUNTRY", property="country", jdbcType=JdbcType.NVARCHAR),
        @Result(column="POSTCODE", property="postcode", jdbcType=JdbcType.NVARCHAR),
        @Result(column="REGION", property="region", jdbcType=JdbcType.NVARCHAR),
        @Result(column="CUST_LEVEL", property="custLevel", jdbcType=JdbcType.NVARCHAR),
        @Result(column="CUST_GROUP", property="custGroup", jdbcType=JdbcType.NVARCHAR),
        @Result(column="VIP_NO", property="vipNo", jdbcType=JdbcType.NVARCHAR),
        @Result(column="VIP_LEVEL", property="vipLevel", jdbcType=JdbcType.NVARCHAR),
        @Result(column="VIP_GROUP", property="vipGroup", jdbcType=JdbcType.NVARCHAR),
        @Result(column="CUST_POINT_FLAG", property="custPointFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="POINT", property="point", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUST_SOURCE", property="custSource", jdbcType=JdbcType.NVARCHAR),
        @Result(column="VALID_FROM", property="validFrom", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="VALID_TO", property="validTo", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="INV_TYPE", property="invType", jdbcType=JdbcType.NVARCHAR),
        @Result(column="INV_TITLE", property="invTitle", jdbcType=JdbcType.NVARCHAR),
        @Result(column="INV_TAXNO", property="invTaxno", jdbcType=JdbcType.NVARCHAR),
        @Result(column="TAX_CODE", property="taxCode", jdbcType=JdbcType.NVARCHAR),
        @Result(column="IC_REGISTER_NO", property="icRegisterNo", jdbcType=JdbcType.NVARCHAR),
        @Result(column="REGISTER_DATE", property="registerDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="REGISTER_ADDRESS", property="registerAddress", jdbcType=JdbcType.NVARCHAR),
        @Result(column="REGISTER_TRADEMARK_NO", property="registerTrademarkNo", jdbcType=JdbcType.NVARCHAR),
        @Result(column="REGISTER_FUND", property="registerFund", jdbcType=JdbcType.NVARCHAR),
        @Result(column="REGISTER_FUND_CURRY", property="registerFundCurry", jdbcType=JdbcType.NVARCHAR),
        @Result(column="REPR", property="repr", jdbcType=JdbcType.NVARCHAR),
        @Result(column="COMP_NAME", property="compName", jdbcType=JdbcType.NVARCHAR),
        @Result(column="COMP_PROP", property="compProp", jdbcType=JdbcType.NVARCHAR),
        @Result(column="COMP_SCALE", property="compScale", jdbcType=JdbcType.NVARCHAR),
        @Result(column="COMP_BUSSADDR", property="compBussaddr", jdbcType=JdbcType.NVARCHAR),
        @Result(column="COMP_MAINBUSS", property="compMainbuss", jdbcType=JdbcType.NVARCHAR),
        @Result(column="COMP_BUSSRANGE", property="compBussrange", jdbcType=JdbcType.NVARCHAR),
        @Result(column="REMARK", property="remark", jdbcType=JdbcType.NVARCHAR),
        @Result(column="OUTER_CODE", property="outerCode", jdbcType=JdbcType.NVARCHAR),
        @Result(column="CREATE_USER_ID", property="createUserId", jdbcType=JdbcType.DECIMAL),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFY_USER_ID", property="modifyUserId", jdbcType=JdbcType.DECIMAL),
        @Result(column="MODIFY_TIME", property="modifyTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="AUDIT_DATA_VERSION", property="auditDataVersion", jdbcType=JdbcType.DECIMAL),
        @Result(column="DELETE_FLAG", property="deleteFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAY_METHOD", property="payMethod", jdbcType=JdbcType.NVARCHAR),
        @Result(column="TAXPAYER_TYPE", property="taxpayerType", jdbcType=JdbcType.NVARCHAR),
        @Result(column="OU_CODE", property="ouCode", jdbcType=JdbcType.NVARCHAR)
    })
    TPbCust selectByPrimaryKey(Long id);

    @Select({
        "select",
        "ID, TENANT_ID, OU_ID, ORG_ID, CUST_CODE, CUST_NAME, CUST_ABBR, CUST_TYPE, CUST_STATUS, ",
        "PID, ADDR_NO, PINYIN, PINYIN_SH, COMP_CAPITAL, AGENT_EMP_ID, CUST_CURR, CREDIT_LIMIT, ",
        "CREDIT_BAL, PAYMENT_TERM, SETTLE_TYPE, RECON_PERIOD, SETTLE_MONTHLY_DAY, DEF_ORG_ID, ",
        "DEF_WH_ID, C1, C2, C3, COUNTRY, POSTCODE, REGION, CUST_LEVEL, CUST_GROUP, VIP_NO, ",
        "VIP_LEVEL, VIP_GROUP, CUST_POINT_FLAG, POINT, CUST_SOURCE, VALID_FROM, VALID_TO, ",
        "INV_TYPE, INV_TITLE, INV_TAXNO, TAX_CODE, IC_REGISTER_NO, REGISTER_DATE, REGISTER_ADDRESS, ",
        "REGISTER_TRADEMARK_NO, REGISTER_FUND, REGISTER_FUND_CURRY, REPR, COMP_NAME, ",
        "COMP_PROP, COMP_SCALE, COMP_BUSSADDR, COMP_MAINBUSS, COMP_BUSSRANGE, REMARK, ",
        "OUTER_CODE, CREATE_USER_ID, CREATE_TIME, MODIFY_USER_ID, MODIFY_TIME, AUDIT_DATA_VERSION, ",
        "DELETE_FLAG, PAY_METHOD, TAXPAYER_TYPE, OU_CODE",
        "from PB_CUST"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.DECIMAL, id=true),
        @Result(column="TENANT_ID", property="tenantId", jdbcType=JdbcType.DECIMAL),
        @Result(column="OU_ID", property="ouId", jdbcType=JdbcType.DECIMAL),
        @Result(column="ORG_ID", property="orgId", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUST_CODE", property="custCode", jdbcType=JdbcType.NVARCHAR),
        @Result(column="CUST_NAME", property="custName", jdbcType=JdbcType.NVARCHAR),
        @Result(column="CUST_ABBR", property="custAbbr", jdbcType=JdbcType.NVARCHAR),
        @Result(column="CUST_TYPE", property="custType", jdbcType=JdbcType.NVARCHAR),
        @Result(column="CUST_STATUS", property="custStatus", jdbcType=JdbcType.NVARCHAR),
        @Result(column="PID", property="pid", jdbcType=JdbcType.DECIMAL),
        @Result(column="ADDR_NO", property="addrNo", jdbcType=JdbcType.DECIMAL),
        @Result(column="PINYIN", property="pinyin", jdbcType=JdbcType.NVARCHAR),
        @Result(column="PINYIN_SH", property="pinyinSh", jdbcType=JdbcType.NVARCHAR),
        @Result(column="COMP_CAPITAL", property="compCapital", jdbcType=JdbcType.NVARCHAR),
        @Result(column="AGENT_EMP_ID", property="agentEmpId", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUST_CURR", property="custCurr", jdbcType=JdbcType.NVARCHAR),
        @Result(column="CREDIT_LIMIT", property="creditLimit", jdbcType=JdbcType.DECIMAL),
        @Result(column="CREDIT_BAL", property="creditBal", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAYMENT_TERM", property="paymentTerm", jdbcType=JdbcType.NVARCHAR),
        @Result(column="SETTLE_TYPE", property="settleType", jdbcType=JdbcType.NVARCHAR),
        @Result(column="RECON_PERIOD", property="reconPeriod", jdbcType=JdbcType.NVARCHAR),
        @Result(column="SETTLE_MONTHLY_DAY", property="settleMonthlyDay", jdbcType=JdbcType.DECIMAL),
        @Result(column="DEF_ORG_ID", property="defOrgId", jdbcType=JdbcType.DECIMAL),
        @Result(column="DEF_WH_ID", property="defWhId", jdbcType=JdbcType.DECIMAL),
        @Result(column="C1", property="c1", jdbcType=JdbcType.NVARCHAR),
        @Result(column="C2", property="c2", jdbcType=JdbcType.NVARCHAR),
        @Result(column="C3", property="c3", jdbcType=JdbcType.NVARCHAR),
        @Result(column="COUNTRY", property="country", jdbcType=JdbcType.NVARCHAR),
        @Result(column="POSTCODE", property="postcode", jdbcType=JdbcType.NVARCHAR),
        @Result(column="REGION", property="region", jdbcType=JdbcType.NVARCHAR),
        @Result(column="CUST_LEVEL", property="custLevel", jdbcType=JdbcType.NVARCHAR),
        @Result(column="CUST_GROUP", property="custGroup", jdbcType=JdbcType.NVARCHAR),
        @Result(column="VIP_NO", property="vipNo", jdbcType=JdbcType.NVARCHAR),
        @Result(column="VIP_LEVEL", property="vipLevel", jdbcType=JdbcType.NVARCHAR),
        @Result(column="VIP_GROUP", property="vipGroup", jdbcType=JdbcType.NVARCHAR),
        @Result(column="CUST_POINT_FLAG", property="custPointFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="POINT", property="point", jdbcType=JdbcType.DECIMAL),
        @Result(column="CUST_SOURCE", property="custSource", jdbcType=JdbcType.NVARCHAR),
        @Result(column="VALID_FROM", property="validFrom", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="VALID_TO", property="validTo", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="INV_TYPE", property="invType", jdbcType=JdbcType.NVARCHAR),
        @Result(column="INV_TITLE", property="invTitle", jdbcType=JdbcType.NVARCHAR),
        @Result(column="INV_TAXNO", property="invTaxno", jdbcType=JdbcType.NVARCHAR),
        @Result(column="TAX_CODE", property="taxCode", jdbcType=JdbcType.NVARCHAR),
        @Result(column="IC_REGISTER_NO", property="icRegisterNo", jdbcType=JdbcType.NVARCHAR),
        @Result(column="REGISTER_DATE", property="registerDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="REGISTER_ADDRESS", property="registerAddress", jdbcType=JdbcType.NVARCHAR),
        @Result(column="REGISTER_TRADEMARK_NO", property="registerTrademarkNo", jdbcType=JdbcType.NVARCHAR),
        @Result(column="REGISTER_FUND", property="registerFund", jdbcType=JdbcType.NVARCHAR),
        @Result(column="REGISTER_FUND_CURRY", property="registerFundCurry", jdbcType=JdbcType.NVARCHAR),
        @Result(column="REPR", property="repr", jdbcType=JdbcType.NVARCHAR),
        @Result(column="COMP_NAME", property="compName", jdbcType=JdbcType.NVARCHAR),
        @Result(column="COMP_PROP", property="compProp", jdbcType=JdbcType.NVARCHAR),
        @Result(column="COMP_SCALE", property="compScale", jdbcType=JdbcType.NVARCHAR),
        @Result(column="COMP_BUSSADDR", property="compBussaddr", jdbcType=JdbcType.NVARCHAR),
        @Result(column="COMP_MAINBUSS", property="compMainbuss", jdbcType=JdbcType.NVARCHAR),
        @Result(column="COMP_BUSSRANGE", property="compBussrange", jdbcType=JdbcType.NVARCHAR),
        @Result(column="REMARK", property="remark", jdbcType=JdbcType.NVARCHAR),
        @Result(column="OUTER_CODE", property="outerCode", jdbcType=JdbcType.NVARCHAR),
        @Result(column="CREATE_USER_ID", property="createUserId", jdbcType=JdbcType.DECIMAL),
        @Result(column="CREATE_TIME", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="MODIFY_USER_ID", property="modifyUserId", jdbcType=JdbcType.DECIMAL),
        @Result(column="MODIFY_TIME", property="modifyTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="AUDIT_DATA_VERSION", property="auditDataVersion", jdbcType=JdbcType.DECIMAL),
        @Result(column="DELETE_FLAG", property="deleteFlag", jdbcType=JdbcType.DECIMAL),
        @Result(column="PAY_METHOD", property="payMethod", jdbcType=JdbcType.NVARCHAR),
        @Result(column="TAXPAYER_TYPE", property="taxpayerType", jdbcType=JdbcType.NVARCHAR),
        @Result(column="OU_CODE", property="ouCode", jdbcType=JdbcType.NVARCHAR)
    })
    List<TPbCust> selectAll();

    @Update({
        "update PB_CUST",
        "set TENANT_ID = #{tenantId,jdbcType=DECIMAL},",
          "OU_ID = #{ouId,jdbcType=DECIMAL},",
          "ORG_ID = #{orgId,jdbcType=DECIMAL},",
          "CUST_CODE = #{custCode,jdbcType=NVARCHAR},",
          "CUST_NAME = #{custName,jdbcType=NVARCHAR},",
          "CUST_ABBR = #{custAbbr,jdbcType=NVARCHAR},",
          "CUST_TYPE = #{custType,jdbcType=NVARCHAR},",
          "CUST_STATUS = #{custStatus,jdbcType=NVARCHAR},",
          "PID = #{pid,jdbcType=DECIMAL},",
          "ADDR_NO = #{addrNo,jdbcType=DECIMAL},",
          "PINYIN = #{pinyin,jdbcType=NVARCHAR},",
          "PINYIN_SH = #{pinyinSh,jdbcType=NVARCHAR},",
          "COMP_CAPITAL = #{compCapital,jdbcType=NVARCHAR},",
          "AGENT_EMP_ID = #{agentEmpId,jdbcType=DECIMAL},",
          "CUST_CURR = #{custCurr,jdbcType=NVARCHAR},",
          "CREDIT_LIMIT = #{creditLimit,jdbcType=DECIMAL},",
          "CREDIT_BAL = #{creditBal,jdbcType=DECIMAL},",
          "PAYMENT_TERM = #{paymentTerm,jdbcType=NVARCHAR},",
          "SETTLE_TYPE = #{settleType,jdbcType=NVARCHAR},",
          "RECON_PERIOD = #{reconPeriod,jdbcType=NVARCHAR},",
          "SETTLE_MONTHLY_DAY = #{settleMonthlyDay,jdbcType=DECIMAL},",
          "DEF_ORG_ID = #{defOrgId,jdbcType=DECIMAL},",
          "DEF_WH_ID = #{defWhId,jdbcType=DECIMAL},",
          "C1 = #{c1,jdbcType=NVARCHAR},",
          "C2 = #{c2,jdbcType=NVARCHAR},",
          "C3 = #{c3,jdbcType=NVARCHAR},",
          "COUNTRY = #{country,jdbcType=NVARCHAR},",
          "POSTCODE = #{postcode,jdbcType=NVARCHAR},",
          "REGION = #{region,jdbcType=NVARCHAR},",
          "CUST_LEVEL = #{custLevel,jdbcType=NVARCHAR},",
          "CUST_GROUP = #{custGroup,jdbcType=NVARCHAR},",
          "VIP_NO = #{vipNo,jdbcType=NVARCHAR},",
          "VIP_LEVEL = #{vipLevel,jdbcType=NVARCHAR},",
          "VIP_GROUP = #{vipGroup,jdbcType=NVARCHAR},",
          "CUST_POINT_FLAG = #{custPointFlag,jdbcType=DECIMAL},",
          "POINT = #{point,jdbcType=DECIMAL},",
          "CUST_SOURCE = #{custSource,jdbcType=NVARCHAR},",
          "VALID_FROM = #{validFrom,jdbcType=TIMESTAMP},",
          "VALID_TO = #{validTo,jdbcType=TIMESTAMP},",
          "INV_TYPE = #{invType,jdbcType=NVARCHAR},",
          "INV_TITLE = #{invTitle,jdbcType=NVARCHAR},",
          "INV_TAXNO = #{invTaxno,jdbcType=NVARCHAR},",
          "TAX_CODE = #{taxCode,jdbcType=NVARCHAR},",
          "IC_REGISTER_NO = #{icRegisterNo,jdbcType=NVARCHAR},",
          "REGISTER_DATE = #{registerDate,jdbcType=TIMESTAMP},",
          "REGISTER_ADDRESS = #{registerAddress,jdbcType=NVARCHAR},",
          "REGISTER_TRADEMARK_NO = #{registerTrademarkNo,jdbcType=NVARCHAR},",
          "REGISTER_FUND = #{registerFund,jdbcType=NVARCHAR},",
          "REGISTER_FUND_CURRY = #{registerFundCurry,jdbcType=NVARCHAR},",
          "REPR = #{repr,jdbcType=NVARCHAR},",
          "COMP_NAME = #{compName,jdbcType=NVARCHAR},",
          "COMP_PROP = #{compProp,jdbcType=NVARCHAR},",
          "COMP_SCALE = #{compScale,jdbcType=NVARCHAR},",
          "COMP_BUSSADDR = #{compBussaddr,jdbcType=NVARCHAR},",
          "COMP_MAINBUSS = #{compMainbuss,jdbcType=NVARCHAR},",
          "COMP_BUSSRANGE = #{compBussrange,jdbcType=NVARCHAR},",
          "REMARK = #{remark,jdbcType=NVARCHAR},",
          "OUTER_CODE = #{outerCode,jdbcType=NVARCHAR},",
          "CREATE_USER_ID = #{createUserId,jdbcType=DECIMAL},",
          "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
          "MODIFY_USER_ID = #{modifyUserId,jdbcType=DECIMAL},",
          "MODIFY_TIME = #{modifyTime,jdbcType=TIMESTAMP},",
          "AUDIT_DATA_VERSION = #{auditDataVersion,jdbcType=DECIMAL},",
          "DELETE_FLAG = #{deleteFlag,jdbcType=DECIMAL},",
          "PAY_METHOD = #{payMethod,jdbcType=NVARCHAR},",
          "TAXPAYER_TYPE = #{taxpayerType,jdbcType=NVARCHAR},",
          "OU_CODE = #{ouCode,jdbcType=NVARCHAR}",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(TPbCust record);
}