package com.el.mbg.mapper;

import com.el.mbg.domain.TPbItem;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TPbItemMapper {
    @Delete({
        "delete from PB_ITEM",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int deleteByPrimaryKey(Long id);

    @Insert({
        "insert into PB_ITEM (ID, TENANT_ID, ",
        "OU_ID, ORG_ID, ITEM_CODE, ",
        "ITEM_NAME, ITEM_ABBR, ",
        "ITEM_TITLE, ITEM_DESC, ",
        "SUB_TITLE, MEM_CODE, ",
        "STORE_TYPE, PINYIN, ",
        "PINYIN_SH, PROMOTION_INFO, ",
        "KEYWORDS, MARKS, ",
        "ITEM_STATUS, ITEM_STATUS2, ",
        "LISTING_STATUS, C1_CODE, ",
        "C2_CODE, C3_CODE, ",
        "UOM, UOM2, SHIP_UOM, ",
        "GROSS_WEIGHT, NET_WEIGHT, ",
        "WEIGHT_UOM, VOLUME, ",
        "MOQ, SAFE_QTY, MAX_QTY, ",
        "SALE_PRICE, PRICE_GROUP, ",
        "PRICE_PERIOD, BRAND, ",
        "MATERIAL, GRADE, ",
        "STANDARD, SURFACE, ",
        "ORIGIN, SPEC, ",
        "P1, P2, P3, ",
        "P4, P5, P6, ",
        "P7, P8, REMARK, ",
        "OUTER_CODE, CREATE_USER_ID, ",
        "CREATE_TIME, MODIFY_USER_ID, ",
        "MODIFY_TIME, AUDIT_DATA_VERSION, ",
        "DELETE_FLAG, UOM3, ",
        "UOM4, UOM5, UOM6, ",
        "UOM7, UOM8, UOM9, ",
        "UOM10, INTF_STATUS, ",
        "INTF_TIME, ITEM_PROP, ",
        "REP_ITEM_ID, OTHER_PROP1, ",
        "OTHER_PROP2, OTHER_PROP3, ",
        "OTHER_PROP4, OTHER_PROP5, ",
        "OTHER_PROP6, OTHER_PROP7, ",
        "OTHER_PROP8, OTHER_PROP9, ",
        "OTHER_PROP10, OTHER_PROP11, ",
        "OTHER_PROP12, OTHER_PROP13, ",
        "OTHER_PROP14, OTHER_PROP15, ",
        "OTHER_PROP16, OTHER_PROP17, ",
        "OTHER_PROP18, ITEM_STAKE_TYPE, ",
        "OU_CODE,SPE8SPXZ,SPE8CJWLBM, SPAN8DSC)",
        "values (#{id,jdbcType=DECIMAL}, #{tenantId,jdbcType=DECIMAL}, ",
        "#{ouId,jdbcType=DECIMAL}, #{orgId,jdbcType=DECIMAL}, #{itemCode,jdbcType=NVARCHAR}, ",
        "#{itemName,jdbcType=NVARCHAR}, #{itemAbbr,jdbcType=NVARCHAR}, ",
        "#{itemTitle,jdbcType=NVARCHAR}, #{itemDesc,jdbcType=NVARCHAR}, ",
        "#{subTitle,jdbcType=NVARCHAR}, #{memCode,jdbcType=NVARCHAR}, ",
        "#{storeType,jdbcType=NVARCHAR}, #{pinyin,jdbcType=NVARCHAR}, ",
        "#{pinyinSh,jdbcType=NVARCHAR}, #{promotionInfo,jdbcType=NVARCHAR}, ",
        "#{keywords,jdbcType=NVARCHAR}, #{marks,jdbcType=NVARCHAR}, ",
        "#{itemStatus,jdbcType=NVARCHAR}, #{itemStatus2,jdbcType=NVARCHAR}, ",
        "#{listingStatus,jdbcType=NVARCHAR}, #{c1Code,jdbcType=NVARCHAR}, ",
        "#{c2Code,jdbcType=NVARCHAR}, #{c3Code,jdbcType=NVARCHAR}, ",
        "#{uom,jdbcType=NVARCHAR}, #{uom2,jdbcType=NVARCHAR}, #{shipUom,jdbcType=NVARCHAR}, ",
        "#{grossWeight,jdbcType=DECIMAL}, #{netWeight,jdbcType=DECIMAL}, ",
        "#{weightUom,jdbcType=NVARCHAR}, #{volume,jdbcType=DECIMAL}, ",
        "#{moq,jdbcType=DECIMAL}, #{safeQty,jdbcType=DECIMAL}, #{maxQty,jdbcType=DECIMAL}, ",
        "#{salePrice,jdbcType=DECIMAL}, #{priceGroup,jdbcType=NVARCHAR}, ",
        "#{pricePeriod,jdbcType=NVARCHAR}, #{brand,jdbcType=NVARCHAR}, ",
        "#{material,jdbcType=NVARCHAR}, #{grade,jdbcType=NVARCHAR}, ",
        "#{standard,jdbcType=NVARCHAR}, #{surface,jdbcType=NVARCHAR}, ",
        "#{origin,jdbcType=NVARCHAR}, #{spec,jdbcType=NVARCHAR}, ",
        "#{p1,jdbcType=NVARCHAR}, #{p2,jdbcType=NVARCHAR}, #{p3,jdbcType=NVARCHAR}, ",
        "#{p4,jdbcType=NVARCHAR}, #{p5,jdbcType=NVARCHAR}, #{p6,jdbcType=NVARCHAR}, ",
        "#{p7,jdbcType=NVARCHAR}, #{p8,jdbcType=NVARCHAR}, #{remark,jdbcType=NVARCHAR}, ",
        "#{outerCode,jdbcType=NVARCHAR}, #{createUserId,jdbcType=DECIMAL}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{modifyUserId,jdbcType=DECIMAL}, ",
        "#{modifyTime,jdbcType=TIMESTAMP}, #{auditDataVersion,jdbcType=DECIMAL}, ",
        "#{deleteFlag,jdbcType=DECIMAL}, #{uom3,jdbcType=NVARCHAR}, ",
        "#{uom4,jdbcType=NVARCHAR}, #{uom5,jdbcType=NVARCHAR}, #{uom6,jdbcType=NVARCHAR}, ",
        "#{uom7,jdbcType=NVARCHAR}, #{uom8,jdbcType=NVARCHAR}, #{uom9,jdbcType=NVARCHAR}, ",
        "#{uom10,jdbcType=NVARCHAR}, #{intfStatus,jdbcType=NVARCHAR}, ",
        "#{intfTime,jdbcType=TIMESTAMP}, #{itemProp,jdbcType=NVARCHAR}, ",
        "#{repItemId,jdbcType=DECIMAL}, #{otherProp1,jdbcType=NVARCHAR}, ",
        "#{otherProp2,jdbcType=NVARCHAR}, #{otherProp3,jdbcType=NVARCHAR}, ",
        "#{otherProp4,jdbcType=NVARCHAR}, #{otherProp5,jdbcType=NVARCHAR}, ",
        "#{otherProp6,jdbcType=NVARCHAR}, #{otherProp7,jdbcType=NVARCHAR}, ",
        "#{otherProp8,jdbcType=NVARCHAR}, #{otherProp9,jdbcType=NVARCHAR}, ",
        "#{otherProp10,jdbcType=NVARCHAR}, #{otherProp11,jdbcType=NVARCHAR}, ",
        "#{otherProp12,jdbcType=NVARCHAR}, #{otherProp13,jdbcType=NVARCHAR}, ",
        "#{otherProp14,jdbcType=NVARCHAR}, #{otherProp15,jdbcType=NVARCHAR}, ",
        "#{otherProp16,jdbcType=NVARCHAR}, #{otherProp17,jdbcType=NVARCHAR}, ",
        "#{otherProp18,jdbcType=NVARCHAR}, #{itemStakeType,jdbcType=NVARCHAR}, ",
        "#{ouCode,jdbcType=NVARCHAR},#{spe8spxz,jdbcType=NVARCHAR},#{spe8cjwlbm,jdbcType=NVARCHAR},#{span8dsc,jdbcType=NVARCHAR})"
    })
    @SelectKey(statement = "SELECT SEQ_PB_ITEM.NEXTVAL FROM DUAL", keyProperty = "id", before = true, resultType = Long.class)
    int insert(TPbItem record);

    @Select({
        "select",
        "ID, TENANT_ID, OU_ID, ORG_ID, ITEM_CODE, ITEM_NAME, ITEM_ABBR, ITEM_TITLE, ITEM_DESC, ",
        "SUB_TITLE, MEM_CODE, STORE_TYPE, PINYIN, PINYIN_SH, PROMOTION_INFO, KEYWORDS, ",
        "MARKS, ITEM_STATUS, ITEM_STATUS2, LISTING_STATUS, C1_CODE, C2_CODE, C3_CODE, ",
        "UOM, UOM2, SHIP_UOM, GROSS_WEIGHT, NET_WEIGHT, WEIGHT_UOM, VOLUME, MOQ, SAFE_QTY, ",
        "MAX_QTY, SALE_PRICE, PRICE_GROUP, PRICE_PERIOD, BRAND, MATERIAL, GRADE, STANDARD, ",
        "SURFACE, ORIGIN, SPEC, P1, P2, P3, P4, P5, P6, P7, P8, REMARK, OUTER_CODE, CREATE_USER_ID, ",
        "CREATE_TIME, MODIFY_USER_ID, MODIFY_TIME, AUDIT_DATA_VERSION, DELETE_FLAG, UOM3, ",
        "UOM4, UOM5, UOM6, UOM7, UOM8, UOM9, UOM10, INTF_STATUS, INTF_TIME, ITEM_PROP, ",
        "REP_ITEM_ID, OTHER_PROP1, OTHER_PROP2, OTHER_PROP3, OTHER_PROP4, OTHER_PROP5, ",
        "OTHER_PROP6, OTHER_PROP7, OTHER_PROP8, OTHER_PROP9, OTHER_PROP10, OTHER_PROP11, ",
        "OTHER_PROP12, OTHER_PROP13, OTHER_PROP14, OTHER_PROP15, OTHER_PROP16, OTHER_PROP17, ",
        "OTHER_PROP18, ITEM_STAKE_TYPE, OU_CODE, SPE8SPXZ, SPE8CJWLBM, SPAN8DSC",
        "from PB_ITEM",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    @Results({
        @Result(column = "ID", property = "id", jdbcType = JdbcType.DECIMAL, id = true),
        @Result(column = "TENANT_ID", property = "tenantId", jdbcType = JdbcType.DECIMAL),
        @Result(column = "OU_ID", property = "ouId", jdbcType = JdbcType.DECIMAL),
        @Result(column = "ORG_ID", property = "orgId", jdbcType = JdbcType.DECIMAL),
        @Result(column = "ITEM_CODE", property = "itemCode", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "ITEM_NAME", property = "itemName", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "ITEM_ABBR", property = "itemAbbr", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "ITEM_TITLE", property = "itemTitle", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "ITEM_DESC", property = "itemDesc", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "SUB_TITLE", property = "subTitle", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "MEM_CODE", property = "memCode", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "STORE_TYPE", property = "storeType", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "PINYIN", property = "pinyin", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "PINYIN_SH", property = "pinyinSh", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "PROMOTION_INFO", property = "promotionInfo", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "KEYWORDS", property = "keywords", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "MARKS", property = "marks", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "ITEM_STATUS", property = "itemStatus", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "ITEM_STATUS2", property = "itemStatus2", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "LISTING_STATUS", property = "listingStatus", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "C1_CODE", property = "c1Code", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "C2_CODE", property = "c2Code", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "C3_CODE", property = "c3Code", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "UOM", property = "uom", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "UOM2", property = "uom2", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "SHIP_UOM", property = "shipUom", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "GROSS_WEIGHT", property = "grossWeight", jdbcType = JdbcType.DECIMAL),
        @Result(column = "NET_WEIGHT", property = "netWeight", jdbcType = JdbcType.DECIMAL),
        @Result(column = "WEIGHT_UOM", property = "weightUom", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "VOLUME", property = "volume", jdbcType = JdbcType.DECIMAL),
        @Result(column = "MOQ", property = "moq", jdbcType = JdbcType.DECIMAL),
        @Result(column = "SAFE_QTY", property = "safeQty", jdbcType = JdbcType.DECIMAL),
        @Result(column = "MAX_QTY", property = "maxQty", jdbcType = JdbcType.DECIMAL),
        @Result(column = "SALE_PRICE", property = "salePrice", jdbcType = JdbcType.DECIMAL),
        @Result(column = "PRICE_GROUP", property = "priceGroup", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "PRICE_PERIOD", property = "pricePeriod", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "BRAND", property = "brand", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "MATERIAL", property = "material", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "GRADE", property = "grade", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "STANDARD", property = "standard", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "SURFACE", property = "surface", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "ORIGIN", property = "origin", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "SPEC", property = "spec", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "P1", property = "p1", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "P2", property = "p2", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "P3", property = "p3", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "P4", property = "p4", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "P5", property = "p5", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "P6", property = "p6", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "P7", property = "p7", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "P8", property = "p8", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "REMARK", property = "remark", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OUTER_CODE", property = "outerCode", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "CREATE_USER_ID", property = "createUserId", jdbcType = JdbcType.DECIMAL),
        @Result(column = "CREATE_TIME", property = "createTime", jdbcType = JdbcType.TIMESTAMP),
        @Result(column = "MODIFY_USER_ID", property = "modifyUserId", jdbcType = JdbcType.DECIMAL),
        @Result(column = "MODIFY_TIME", property = "modifyTime", jdbcType = JdbcType.TIMESTAMP),
        @Result(column = "AUDIT_DATA_VERSION", property = "auditDataVersion", jdbcType = JdbcType.DECIMAL),
        @Result(column = "DELETE_FLAG", property = "deleteFlag", jdbcType = JdbcType.DECIMAL),
        @Result(column = "UOM3", property = "uom3", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "UOM4", property = "uom4", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "UOM5", property = "uom5", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "UOM6", property = "uom6", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "UOM7", property = "uom7", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "UOM8", property = "uom8", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "UOM9", property = "uom9", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "UOM10", property = "uom10", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "INTF_STATUS", property = "intfStatus", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "INTF_TIME", property = "intfTime", jdbcType = JdbcType.TIMESTAMP),
        @Result(column = "ITEM_PROP", property = "itemProp", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "REP_ITEM_ID", property = "repItemId", jdbcType = JdbcType.DECIMAL),
        @Result(column = "OTHER_PROP1", property = "otherProp1", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP2", property = "otherProp2", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP3", property = "otherProp3", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP4", property = "otherProp4", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP5", property = "otherProp5", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP6", property = "otherProp6", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP7", property = "otherProp7", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP8", property = "otherProp8", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP9", property = "otherProp9", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP10", property = "otherProp10", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP11", property = "otherProp11", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP12", property = "otherProp12", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP13", property = "otherProp13", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP14", property = "otherProp14", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP15", property = "otherProp15", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP16", property = "otherProp16", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP17", property = "otherProp17", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP18", property = "otherProp18", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "ITEM_STAKE_TYPE", property = "itemStakeType", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OU_CODE", property = "ouCode", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "SPE8SPXZ", property = "spe8spxz", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "SPE8CJWLBM", property = "spe8cjwlbm", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "SPAN8DSC", property = "span8dsc", jdbcType = JdbcType.NVARCHAR)
    })
    TPbItem selectByPrimaryKey(Long id);

    @Select({
        "select",
        "ID, TENANT_ID, OU_ID, ORG_ID, ITEM_CODE, ITEM_NAME, ITEM_ABBR, ITEM_TITLE, ITEM_DESC, ",
        "SUB_TITLE, MEM_CODE, STORE_TYPE, PINYIN, PINYIN_SH, PROMOTION_INFO, KEYWORDS, ",
        "MARKS, ITEM_STATUS, ITEM_STATUS2, LISTING_STATUS, C1_CODE, C2_CODE, C3_CODE, ",
        "UOM, UOM2, SHIP_UOM, GROSS_WEIGHT, NET_WEIGHT, WEIGHT_UOM, VOLUME, MOQ, SAFE_QTY, ",
        "MAX_QTY, SALE_PRICE, PRICE_GROUP, PRICE_PERIOD, BRAND, MATERIAL, GRADE, STANDARD, ",
        "SURFACE, ORIGIN, SPEC, P1, P2, P3, P4, P5, P6, P7, P8, REMARK, OUTER_CODE, CREATE_USER_ID, ",
        "CREATE_TIME, MODIFY_USER_ID, MODIFY_TIME, AUDIT_DATA_VERSION, DELETE_FLAG, UOM3, ",
        "UOM4, UOM5, UOM6, UOM7, UOM8, UOM9, UOM10, INTF_STATUS, INTF_TIME, ITEM_PROP, ",
        "REP_ITEM_ID, OTHER_PROP1, OTHER_PROP2, OTHER_PROP3, OTHER_PROP4, OTHER_PROP5, ",
        "OTHER_PROP6, OTHER_PROP7, OTHER_PROP8, OTHER_PROP9, OTHER_PROP10, OTHER_PROP11, ",
        "OTHER_PROP12, OTHER_PROP13, OTHER_PROP14, OTHER_PROP15, OTHER_PROP16, OTHER_PROP17, ",
        "OTHER_PROP18, ITEM_STAKE_TYPE, OU_CODE, SPE8SPXZ, SPE8CJWLBM, SPAN8DSC",
        "from PB_ITEM"
    })
    @Results({
        @Result(column = "ID", property = "id", jdbcType = JdbcType.DECIMAL, id = true),
        @Result(column = "TENANT_ID", property = "tenantId", jdbcType = JdbcType.DECIMAL),
        @Result(column = "OU_ID", property = "ouId", jdbcType = JdbcType.DECIMAL),
        @Result(column = "ORG_ID", property = "orgId", jdbcType = JdbcType.DECIMAL),
        @Result(column = "ITEM_CODE", property = "itemCode", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "ITEM_NAME", property = "itemName", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "ITEM_ABBR", property = "itemAbbr", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "ITEM_TITLE", property = "itemTitle", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "ITEM_DESC", property = "itemDesc", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "SUB_TITLE", property = "subTitle", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "MEM_CODE", property = "memCode", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "STORE_TYPE", property = "storeType", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "PINYIN", property = "pinyin", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "PINYIN_SH", property = "pinyinSh", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "PROMOTION_INFO", property = "promotionInfo", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "KEYWORDS", property = "keywords", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "MARKS", property = "marks", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "ITEM_STATUS", property = "itemStatus", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "ITEM_STATUS2", property = "itemStatus2", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "LISTING_STATUS", property = "listingStatus", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "C1_CODE", property = "c1Code", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "C2_CODE", property = "c2Code", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "C3_CODE", property = "c3Code", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "UOM", property = "uom", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "UOM2", property = "uom2", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "SHIP_UOM", property = "shipUom", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "GROSS_WEIGHT", property = "grossWeight", jdbcType = JdbcType.DECIMAL),
        @Result(column = "NET_WEIGHT", property = "netWeight", jdbcType = JdbcType.DECIMAL),
        @Result(column = "WEIGHT_UOM", property = "weightUom", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "VOLUME", property = "volume", jdbcType = JdbcType.DECIMAL),
        @Result(column = "MOQ", property = "moq", jdbcType = JdbcType.DECIMAL),
        @Result(column = "SAFE_QTY", property = "safeQty", jdbcType = JdbcType.DECIMAL),
        @Result(column = "MAX_QTY", property = "maxQty", jdbcType = JdbcType.DECIMAL),
        @Result(column = "SALE_PRICE", property = "salePrice", jdbcType = JdbcType.DECIMAL),
        @Result(column = "PRICE_GROUP", property = "priceGroup", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "PRICE_PERIOD", property = "pricePeriod", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "BRAND", property = "brand", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "MATERIAL", property = "material", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "GRADE", property = "grade", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "STANDARD", property = "standard", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "SURFACE", property = "surface", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "ORIGIN", property = "origin", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "SPEC", property = "spec", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "P1", property = "p1", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "P2", property = "p2", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "P3", property = "p3", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "P4", property = "p4", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "P5", property = "p5", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "P6", property = "p6", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "P7", property = "p7", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "P8", property = "p8", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "REMARK", property = "remark", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OUTER_CODE", property = "outerCode", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "CREATE_USER_ID", property = "createUserId", jdbcType = JdbcType.DECIMAL),
        @Result(column = "CREATE_TIME", property = "createTime", jdbcType = JdbcType.TIMESTAMP),
        @Result(column = "MODIFY_USER_ID", property = "modifyUserId", jdbcType = JdbcType.DECIMAL),
        @Result(column = "MODIFY_TIME", property = "modifyTime", jdbcType = JdbcType.TIMESTAMP),
        @Result(column = "AUDIT_DATA_VERSION", property = "auditDataVersion", jdbcType = JdbcType.DECIMAL),
        @Result(column = "DELETE_FLAG", property = "deleteFlag", jdbcType = JdbcType.DECIMAL),
        @Result(column = "UOM3", property = "uom3", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "UOM4", property = "uom4", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "UOM5", property = "uom5", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "UOM6", property = "uom6", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "UOM7", property = "uom7", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "UOM8", property = "uom8", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "UOM9", property = "uom9", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "UOM10", property = "uom10", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "INTF_STATUS", property = "intfStatus", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "INTF_TIME", property = "intfTime", jdbcType = JdbcType.TIMESTAMP),
        @Result(column = "ITEM_PROP", property = "itemProp", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "REP_ITEM_ID", property = "repItemId", jdbcType = JdbcType.DECIMAL),
        @Result(column = "OTHER_PROP1", property = "otherProp1", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP2", property = "otherProp2", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP3", property = "otherProp3", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP4", property = "otherProp4", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP5", property = "otherProp5", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP6", property = "otherProp6", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP7", property = "otherProp7", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP8", property = "otherProp8", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP9", property = "otherProp9", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP10", property = "otherProp10", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP11", property = "otherProp11", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP12", property = "otherProp12", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP13", property = "otherProp13", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP14", property = "otherProp14", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP15", property = "otherProp15", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP16", property = "otherProp16", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP17", property = "otherProp17", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OTHER_PROP18", property = "otherProp18", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "ITEM_STAKE_TYPE", property = "itemStakeType", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "OU_CODE", property = "ouCode", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "SPE8SPXZ", property = "spe8spxz", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "SPE8CJWLBM", property = "spe8cjwlbm", jdbcType = JdbcType.NVARCHAR),
        @Result(column = "SPAN8DSC", property = "span8dsc", jdbcType = JdbcType.NVARCHAR)


    })
    List<TPbItem> selectAll();

    @Update({
        "update PB_ITEM",
        "set TENANT_ID = #{tenantId,jdbcType=DECIMAL},",
        "OU_ID = #{ouId,jdbcType=DECIMAL},",
        "ORG_ID = #{orgId,jdbcType=DECIMAL},",
        "ITEM_CODE = #{itemCode,jdbcType=NVARCHAR},",
        "ITEM_NAME = #{itemName,jdbcType=NVARCHAR},",
        "ITEM_ABBR = #{itemAbbr,jdbcType=NVARCHAR},",
        "ITEM_TITLE = #{itemTitle,jdbcType=NVARCHAR},",
        "ITEM_DESC = #{itemDesc,jdbcType=NVARCHAR},",
        "SUB_TITLE = #{subTitle,jdbcType=NVARCHAR},",
        "MEM_CODE = #{memCode,jdbcType=NVARCHAR},",
        "STORE_TYPE = #{storeType,jdbcType=NVARCHAR},",
        "PINYIN = #{pinyin,jdbcType=NVARCHAR},",
        "PINYIN_SH = #{pinyinSh,jdbcType=NVARCHAR},",
        "PROMOTION_INFO = #{promotionInfo,jdbcType=NVARCHAR},",
        "KEYWORDS = #{keywords,jdbcType=NVARCHAR},",
        "MARKS = #{marks,jdbcType=NVARCHAR},",
        "ITEM_STATUS = #{itemStatus,jdbcType=NVARCHAR},",
        "ITEM_STATUS2 = #{itemStatus2,jdbcType=NVARCHAR},",
        "LISTING_STATUS = #{listingStatus,jdbcType=NVARCHAR},",
        "C1_CODE = #{c1Code,jdbcType=NVARCHAR},",
        "C2_CODE = #{c2Code,jdbcType=NVARCHAR},",
        "C3_CODE = #{c3Code,jdbcType=NVARCHAR},",
        "UOM = #{uom,jdbcType=NVARCHAR},",
        "UOM2 = #{uom2,jdbcType=NVARCHAR},",
        "SHIP_UOM = #{shipUom,jdbcType=NVARCHAR},",
        "GROSS_WEIGHT = #{grossWeight,jdbcType=DECIMAL},",
        "NET_WEIGHT = #{netWeight,jdbcType=DECIMAL},",
        "WEIGHT_UOM = #{weightUom,jdbcType=NVARCHAR},",
        "VOLUME = #{volume,jdbcType=DECIMAL},",
        "MOQ = #{moq,jdbcType=DECIMAL},",
        "SAFE_QTY = #{safeQty,jdbcType=DECIMAL},",
        "MAX_QTY = #{maxQty,jdbcType=DECIMAL},",
        "SALE_PRICE = #{salePrice,jdbcType=DECIMAL},",
        "PRICE_GROUP = #{priceGroup,jdbcType=NVARCHAR},",
        "PRICE_PERIOD = #{pricePeriod,jdbcType=NVARCHAR},",
        "BRAND = #{brand,jdbcType=NVARCHAR},",
        "MATERIAL = #{material,jdbcType=NVARCHAR},",
        "GRADE = #{grade,jdbcType=NVARCHAR},",
        "STANDARD = #{standard,jdbcType=NVARCHAR},",
        "SURFACE = #{surface,jdbcType=NVARCHAR},",
        "ORIGIN = #{origin,jdbcType=NVARCHAR},",
        "SPEC = #{spec,jdbcType=NVARCHAR},",
        "P1 = #{p1,jdbcType=NVARCHAR},",
        "P2 = #{p2,jdbcType=NVARCHAR},",
        "P3 = #{p3,jdbcType=NVARCHAR},",
        "P4 = #{p4,jdbcType=NVARCHAR},",
        "P5 = #{p5,jdbcType=NVARCHAR},",
        "P6 = #{p6,jdbcType=NVARCHAR},",
        "P7 = #{p7,jdbcType=NVARCHAR},",
        "P8 = #{p8,jdbcType=NVARCHAR},",
        "REMARK = #{remark,jdbcType=NVARCHAR},",
        "OUTER_CODE = #{outerCode,jdbcType=NVARCHAR},",
        "CREATE_USER_ID = #{createUserId,jdbcType=DECIMAL},",
        "CREATE_TIME = #{createTime,jdbcType=TIMESTAMP},",
        "MODIFY_USER_ID = #{modifyUserId,jdbcType=DECIMAL},",
        "MODIFY_TIME = #{modifyTime,jdbcType=TIMESTAMP},",
        "AUDIT_DATA_VERSION = #{auditDataVersion,jdbcType=DECIMAL},",
        "DELETE_FLAG = #{deleteFlag,jdbcType=DECIMAL},",
        "UOM3 = #{uom3,jdbcType=NVARCHAR},",
        "UOM4 = #{uom4,jdbcType=NVARCHAR},",
        "UOM5 = #{uom5,jdbcType=NVARCHAR},",
        "UOM6 = #{uom6,jdbcType=NVARCHAR},",
        "UOM7 = #{uom7,jdbcType=NVARCHAR},",
        "UOM8 = #{uom8,jdbcType=NVARCHAR},",
        "UOM9 = #{uom9,jdbcType=NVARCHAR},",
        "UOM10 = #{uom10,jdbcType=NVARCHAR},",
        "INTF_STATUS = #{intfStatus,jdbcType=NVARCHAR},",
        "INTF_TIME = #{intfTime,jdbcType=TIMESTAMP},",
        "ITEM_PROP = #{itemProp,jdbcType=NVARCHAR},",
        "REP_ITEM_ID = #{repItemId,jdbcType=DECIMAL},",
        "OTHER_PROP1 = #{otherProp1,jdbcType=NVARCHAR},",
        "OTHER_PROP2 = #{otherProp2,jdbcType=NVARCHAR},",
        "OTHER_PROP3 = #{otherProp3,jdbcType=NVARCHAR},",
        "OTHER_PROP4 = #{otherProp4,jdbcType=NVARCHAR},",
        "OTHER_PROP5 = #{otherProp5,jdbcType=NVARCHAR},",
        "OTHER_PROP6 = #{otherProp6,jdbcType=NVARCHAR},",
        "OTHER_PROP7 = #{otherProp7,jdbcType=NVARCHAR},",
        "OTHER_PROP8 = #{otherProp8,jdbcType=NVARCHAR},",
        "OTHER_PROP9 = #{otherProp9,jdbcType=NVARCHAR},",
        "OTHER_PROP10 = #{otherProp10,jdbcType=NVARCHAR},",
        "OTHER_PROP11 = #{otherProp11,jdbcType=NVARCHAR},",
        "OTHER_PROP12 = #{otherProp12,jdbcType=NVARCHAR},",
        "OTHER_PROP13 = #{otherProp13,jdbcType=NVARCHAR},",
        "OTHER_PROP14 = #{otherProp14,jdbcType=NVARCHAR},",
        "OTHER_PROP15 = #{otherProp15,jdbcType=NVARCHAR},",
        "OTHER_PROP16 = #{otherProp16,jdbcType=NVARCHAR},",
        "OTHER_PROP17 = #{otherProp17,jdbcType=NVARCHAR},",
        "OTHER_PROP18 = #{otherProp18,jdbcType=NVARCHAR},",
        "ITEM_STAKE_TYPE = #{itemStakeType,jdbcType=NVARCHAR},",
        "OU_CODE = #{ouCode,jdbcType=NVARCHAR}",
        "SPE8SPXZ = #{spe8spxz,jdbcType=NVARCHAR}",
        "SPE8CJWLBM = #{spe8cjwlbm,jdbcType=NVARCHAR}",
        "SPAN8DSC = #{span8dsc,jdbcType=NVARCHAR}",
        "where ID = #{id,jdbcType=DECIMAL}"
    })
    int updateByPrimaryKey(TPbItem record);
}
