package com.el.mbg.mapper;

import com.el.mbg.domain.VE84211W;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;

public interface VE84211WMapper {
    @Insert({
        "insert into VE84211W (SDKCOO, SDDOCO, ",
        "SDDCTO, SDLNID, ",
        "SDDRQJ, SDTRDJ, ",
        "SDPDDJ, SDADDJ, ",
        "SDIVD, SDCNDJ, SDDGL, ",
        "SDLITM, SDAITM, ",
        "SDLOCN, SDLOTN, ",
        "IOLOT1, FCD01, IOMMEJ, ",
        "SDDSC1, SDDSC2, ",
        "SDLNTY, SDNXTR, ",
        "SDLTTR, SDEMCU, ",
        "SDUOM, SDUORG, SDSOQS, ",
        "SDSOBK, SDSOCN, ",
        "SDSONE, SDUOPN, ",
        "SDQTYT, SDQRLV, ",
        "SDCOMM, SDOTQY, ",
        "SDUPRC, SDAEXP, ",
        "DTTUPRC, DTTAEXP, ",
        "SDAOPN, SDPROV, ",
        "SDTPC, SDAPUM, SDLPRC, ",
        "SDUNCS, SDECST, ",
        "SDCSTO, SDTCST, ",
        "SDINMG, SDPTC, SDRYIN, ",
        "SDACOM, SDCMCG, ",
        "SDRCD, SDSBL, SDSBLT, ",
        "SDLCOD, SDCRR, SDFPRC, ",
        "SDFUP, SDFEA, SDFUC, ",
        "SDFEC, SDURCD, SDURDT, ",
        "SDURAT, SDURAB, ",
        "SDURRF, SDTORG, ",
        "SDUSER, SDPID, SDJOBN, ",
        "SDUPMJ, SDTDAY, ",
        "SDSO16, SDSO17, ",
        "SDSO18, SDSO19, ",
        "SDSO20, SDIR01, ",
        "SDIR02, SDIR03, ",
        "SDIR04, SDIR05, ",
        "SDSOOR, SDPMDT, ",
        "SDRLTM, SDRLDJ, ",
        "SDDRQT, SDADTM, ",
        "SDOPTT, SDPDTT, ",
        "SDKITAMTDOM, SDKITAMTFOR, ",
        "EHE8PTID, EHE8PTTP, ",
        "EHE8PTNUM, EHE8PTLIN, ",
        "SHIP_STATUS)",
        "values (#{sdkcoo,jdbcType=VARCHAR}, #{sddoco,jdbcType=INTEGER}, ",
        "#{sddcto,jdbcType=VARCHAR}, #{sdlnid,jdbcType=INTEGER}, ",
        "#{sddrqj,jdbcType=INTEGER}, #{sdtrdj,jdbcType=INTEGER}, ",
        "#{sdpddj,jdbcType=INTEGER}, #{sdaddj,jdbcType=INTEGER}, ",
        "#{sdivd,jdbcType=INTEGER}, #{sdcndj,jdbcType=INTEGER}, #{sddgl,jdbcType=INTEGER}, ",
        "#{sdlitm,jdbcType=VARCHAR}, #{sdaitm,jdbcType=VARCHAR}, ",
        "#{sdlocn,jdbcType=VARCHAR}, #{sdlotn,jdbcType=VARCHAR}, ",
        "#{iolot1,jdbcType=VARCHAR}, #{fcd01,jdbcType=INTEGER}, #{iommej,jdbcType=INTEGER}, ",
        "#{sddsc1,jdbcType=VARCHAR}, #{sddsc2,jdbcType=VARCHAR}, ",
        "#{sdlnty,jdbcType=VARCHAR}, #{sdnxtr,jdbcType=VARCHAR}, ",
        "#{sdlttr,jdbcType=VARCHAR}, #{sdemcu,jdbcType=VARCHAR}, ",
        "#{sduom,jdbcType=VARCHAR}, #{sduorg,jdbcType=INTEGER}, #{sdsoqs,jdbcType=INTEGER}, ",
        "#{sdsobk,jdbcType=INTEGER}, #{sdsocn,jdbcType=INTEGER}, ",
        "#{sdsone,jdbcType=INTEGER}, #{sduopn,jdbcType=INTEGER}, ",
        "#{sdqtyt,jdbcType=INTEGER}, #{sdqrlv,jdbcType=INTEGER}, ",
        "#{sdcomm,jdbcType=VARCHAR}, #{sdotqy,jdbcType=VARCHAR}, ",
        "#{sduprc,jdbcType=INTEGER}, #{sdaexp,jdbcType=INTEGER}, ",
        "#{dttuprc,jdbcType=INTEGER}, #{dttaexp,jdbcType=INTEGER}, ",
        "#{sdaopn,jdbcType=INTEGER}, #{sdprov,jdbcType=VARCHAR}, ",
        "#{sdtpc,jdbcType=VARCHAR}, #{sdapum,jdbcType=VARCHAR}, #{sdlprc,jdbcType=INTEGER}, ",
        "#{sduncs,jdbcType=INTEGER}, #{sdecst,jdbcType=INTEGER}, ",
        "#{sdcsto,jdbcType=VARCHAR}, #{sdtcst,jdbcType=INTEGER}, ",
        "#{sdinmg,jdbcType=VARCHAR}, #{sdptc,jdbcType=VARCHAR}, #{sdryin,jdbcType=VARCHAR}, ",
        "#{sdacom,jdbcType=VARCHAR}, #{sdcmcg,jdbcType=VARCHAR}, ",
        "#{sdrcd,jdbcType=VARCHAR}, #{sdsbl,jdbcType=VARCHAR}, #{sdsblt,jdbcType=VARCHAR}, ",
        "#{sdlcod,jdbcType=VARCHAR}, #{sdcrr,jdbcType=INTEGER}, #{sdfprc,jdbcType=INTEGER}, ",
        "#{sdfup,jdbcType=INTEGER}, #{sdfea,jdbcType=INTEGER}, #{sdfuc,jdbcType=INTEGER}, ",
        "#{sdfec,jdbcType=INTEGER}, #{sdurcd,jdbcType=VARCHAR}, #{sdurdt,jdbcType=INTEGER}, ",
        "#{sdurat,jdbcType=INTEGER}, #{sdurab,jdbcType=INTEGER}, ",
        "#{sdurrf,jdbcType=VARCHAR}, #{sdtorg,jdbcType=VARCHAR}, ",
        "#{sduser,jdbcType=VARCHAR}, #{sdpid,jdbcType=VARCHAR}, #{sdjobn,jdbcType=VARCHAR}, ",
        "#{sdupmj,jdbcType=INTEGER}, #{sdtday,jdbcType=INTEGER}, ",
        "#{sdso16,jdbcType=VARCHAR}, #{sdso17,jdbcType=VARCHAR}, ",
        "#{sdso18,jdbcType=VARCHAR}, #{sdso19,jdbcType=VARCHAR}, ",
        "#{sdso20,jdbcType=VARCHAR}, #{sdir01,jdbcType=VARCHAR}, ",
        "#{sdir02,jdbcType=VARCHAR}, #{sdir03,jdbcType=VARCHAR}, ",
        "#{sdir04,jdbcType=VARCHAR}, #{sdir05,jdbcType=VARCHAR}, ",
        "#{sdsoor,jdbcType=INTEGER}, #{sdpmdt,jdbcType=INTEGER}, ",
        "#{sdrltm,jdbcType=INTEGER}, #{sdrldj,jdbcType=INTEGER}, ",
        "#{sddrqt,jdbcType=INTEGER}, #{sdadtm,jdbcType=INTEGER}, ",
        "#{sdoptt,jdbcType=INTEGER}, #{sdpdtt,jdbcType=INTEGER}, ",
        "#{sdkitamtdom,jdbcType=INTEGER}, #{sdkitamtfor,jdbcType=INTEGER}, ",
        "#{ehe8ptid,jdbcType=VARCHAR}, #{ehe8pttp,jdbcType=VARCHAR}, ",
        "#{ehe8ptnum,jdbcType=VARCHAR}, #{ehe8ptlin,jdbcType=INTEGER}, ",
        "#{shipStatus,jdbcType=INTEGER})"
    })
    int insert(VE84211W record);

    @Select({
        "select",
        "SDKCOO, SDDOCO, SDDCTO, SDLNID, SDDRQJ, SDTRDJ, SDPDDJ, SDADDJ, SDIVD, SDCNDJ, ",
        "SDDGL, SDLITM, SDAITM, SDLOCN, SDLOTN, IOLOT1, FCD01, IOMMEJ, SDDSC1, SDDSC2, ",
        "SDLNTY, SDNXTR, SDLTTR, SDEMCU, SDUOM, SDUORG, SDSOQS, SDSOBK, SDSOCN, SDSONE, ",
        "SDUOPN, SDQTYT, SDQRLV, SDCOMM, SDOTQY, SDUPRC, SDAEXP, DTTUPRC, DTTAEXP, SDAOPN, ",
        "SDPROV, SDTPC, SDAPUM, SDLPRC, SDUNCS, SDECST, SDCSTO, SDTCST, SDINMG, SDPTC, ",
        "SDRYIN, SDACOM, SDCMCG, SDRCD, SDSBL, SDSBLT, SDLCOD, SDCRR, SDFPRC, SDFUP, ",
        "SDFEA, SDFUC, SDFEC, SDURCD, SDURDT, SDURAT, SDURAB, SDURRF, SDTORG, SDUSER, ",
        "SDPID, SDJOBN, SDUPMJ, SDTDAY, SDSO16, SDSO17, SDSO18, SDSO19, SDSO20, SDIR01, ",
        "SDIR02, SDIR03, SDIR04, SDIR05, SDSOOR, SDPMDT, SDRLTM, SDRLDJ, SDDRQT, SDADTM, ",
        "SDOPTT, SDPDTT, SDKITAMTDOM, SDKITAMTFOR, EHE8PTID, EHE8PTTP, EHE8PTNUM, EHE8PTLIN, ",
        "SHIP_STATUS",
        "from VE84211W"
    })
    @Results({
        @Result(column="SDKCOO", property="sdkcoo", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDDOCO", property="sddoco", jdbcType=JdbcType.INTEGER),
        @Result(column="SDDCTO", property="sddcto", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDLNID", property="sdlnid", jdbcType=JdbcType.INTEGER),
        @Result(column="SDDRQJ", property="sddrqj", jdbcType=JdbcType.INTEGER),
        @Result(column="SDTRDJ", property="sdtrdj", jdbcType=JdbcType.INTEGER),
        @Result(column="SDPDDJ", property="sdpddj", jdbcType=JdbcType.INTEGER),
        @Result(column="SDADDJ", property="sdaddj", jdbcType=JdbcType.INTEGER),
        @Result(column="SDIVD", property="sdivd", jdbcType=JdbcType.INTEGER),
        @Result(column="SDCNDJ", property="sdcndj", jdbcType=JdbcType.INTEGER),
        @Result(column="SDDGL", property="sddgl", jdbcType=JdbcType.INTEGER),
        @Result(column="SDLITM", property="sdlitm", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDAITM", property="sdaitm", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDLOCN", property="sdlocn", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDLOTN", property="sdlotn", jdbcType=JdbcType.VARCHAR),
        @Result(column="IOLOT1", property="iolot1", jdbcType=JdbcType.VARCHAR),
        @Result(column="FCD01", property="fcd01", jdbcType=JdbcType.INTEGER),
        @Result(column="IOMMEJ", property="iommej", jdbcType=JdbcType.INTEGER),
        @Result(column="SDDSC1", property="sddsc1", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDDSC2", property="sddsc2", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDLNTY", property="sdlnty", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDNXTR", property="sdnxtr", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDLTTR", property="sdlttr", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDEMCU", property="sdemcu", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDUOM", property="sduom", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDUORG", property="sduorg", jdbcType=JdbcType.INTEGER),
        @Result(column="SDSOQS", property="sdsoqs", jdbcType=JdbcType.INTEGER),
        @Result(column="SDSOBK", property="sdsobk", jdbcType=JdbcType.INTEGER),
        @Result(column="SDSOCN", property="sdsocn", jdbcType=JdbcType.INTEGER),
        @Result(column="SDSONE", property="sdsone", jdbcType=JdbcType.INTEGER),
        @Result(column="SDUOPN", property="sduopn", jdbcType=JdbcType.INTEGER),
        @Result(column="SDQTYT", property="sdqtyt", jdbcType=JdbcType.INTEGER),
        @Result(column="SDQRLV", property="sdqrlv", jdbcType=JdbcType.INTEGER),
        @Result(column="SDCOMM", property="sdcomm", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDOTQY", property="sdotqy", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDUPRC", property="sduprc", jdbcType=JdbcType.INTEGER),
        @Result(column="SDAEXP", property="sdaexp", jdbcType=JdbcType.INTEGER),
        @Result(column="DTTUPRC", property="dttuprc", jdbcType=JdbcType.INTEGER),
        @Result(column="DTTAEXP", property="dttaexp", jdbcType=JdbcType.INTEGER),
        @Result(column="SDAOPN", property="sdaopn", jdbcType=JdbcType.INTEGER),
        @Result(column="SDPROV", property="sdprov", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDTPC", property="sdtpc", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDAPUM", property="sdapum", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDLPRC", property="sdlprc", jdbcType=JdbcType.INTEGER),
        @Result(column="SDUNCS", property="sduncs", jdbcType=JdbcType.INTEGER),
        @Result(column="SDECST", property="sdecst", jdbcType=JdbcType.INTEGER),
        @Result(column="SDCSTO", property="sdcsto", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDTCST", property="sdtcst", jdbcType=JdbcType.INTEGER),
        @Result(column="SDINMG", property="sdinmg", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDPTC", property="sdptc", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDRYIN", property="sdryin", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDACOM", property="sdacom", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDCMCG", property="sdcmcg", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDRCD", property="sdrcd", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDSBL", property="sdsbl", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDSBLT", property="sdsblt", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDLCOD", property="sdlcod", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDCRR", property="sdcrr", jdbcType=JdbcType.INTEGER),
        @Result(column="SDFPRC", property="sdfprc", jdbcType=JdbcType.INTEGER),
        @Result(column="SDFUP", property="sdfup", jdbcType=JdbcType.INTEGER),
        @Result(column="SDFEA", property="sdfea", jdbcType=JdbcType.INTEGER),
        @Result(column="SDFUC", property="sdfuc", jdbcType=JdbcType.INTEGER),
        @Result(column="SDFEC", property="sdfec", jdbcType=JdbcType.INTEGER),
        @Result(column="SDURCD", property="sdurcd", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDURDT", property="sdurdt", jdbcType=JdbcType.INTEGER),
        @Result(column="SDURAT", property="sdurat", jdbcType=JdbcType.INTEGER),
        @Result(column="SDURAB", property="sdurab", jdbcType=JdbcType.INTEGER),
        @Result(column="SDURRF", property="sdurrf", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDTORG", property="sdtorg", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDUSER", property="sduser", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDPID", property="sdpid", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDJOBN", property="sdjobn", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDUPMJ", property="sdupmj", jdbcType=JdbcType.INTEGER),
        @Result(column="SDTDAY", property="sdtday", jdbcType=JdbcType.INTEGER),
        @Result(column="SDSO16", property="sdso16", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDSO17", property="sdso17", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDSO18", property="sdso18", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDSO19", property="sdso19", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDSO20", property="sdso20", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDIR01", property="sdir01", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDIR02", property="sdir02", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDIR03", property="sdir03", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDIR04", property="sdir04", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDIR05", property="sdir05", jdbcType=JdbcType.VARCHAR),
        @Result(column="SDSOOR", property="sdsoor", jdbcType=JdbcType.INTEGER),
        @Result(column="SDPMDT", property="sdpmdt", jdbcType=JdbcType.INTEGER),
        @Result(column="SDRLTM", property="sdrltm", jdbcType=JdbcType.INTEGER),
        @Result(column="SDRLDJ", property="sdrldj", jdbcType=JdbcType.INTEGER),
        @Result(column="SDDRQT", property="sddrqt", jdbcType=JdbcType.INTEGER),
        @Result(column="SDADTM", property="sdadtm", jdbcType=JdbcType.INTEGER),
        @Result(column="SDOPTT", property="sdoptt", jdbcType=JdbcType.INTEGER),
        @Result(column="SDPDTT", property="sdpdtt", jdbcType=JdbcType.INTEGER),
        @Result(column="SDKITAMTDOM", property="sdkitamtdom", jdbcType=JdbcType.INTEGER),
        @Result(column="SDKITAMTFOR", property="sdkitamtfor", jdbcType=JdbcType.INTEGER),
        @Result(column="EHE8PTID", property="ehe8ptid", jdbcType=JdbcType.VARCHAR),
        @Result(column="EHE8PTTP", property="ehe8pttp", jdbcType=JdbcType.VARCHAR),
        @Result(column="EHE8PTNUM", property="ehe8ptnum", jdbcType=JdbcType.VARCHAR),
        @Result(column="EHE8PTLIN", property="ehe8ptlin", jdbcType=JdbcType.INTEGER),
        @Result(column="SHIP_STATUS", property="shipStatus", jdbcType=JdbcType.INTEGER)
    })
    List<VE84211W> selectAll();
}