--------------------
-- 审计日志
--------------------

--DROP SEQUENCE SEQ_PS_AUDIT_LOG;
CREATE SEQUENCE SEQ_PS_AUDIT_LOG;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_PS_AUDIT_LOG FOR SEQ_PS_AUDIT_LOG;

--DROP TABLE PS_AUDIT_LOG;
CREATE TABLE PS_AUDIT_LOG
(
  ID NUMBER(18, 0) NOT NULL
, OP_USER NVARCHAR2(30) NOT NULL
, OP_TYPE CHAR(1 BYTE) NOT NULL
, OP_BEGIN TIMESTAMP(6) NOT NULL
, OP_END TIMESTAMP(6)
, OP_API VARCHAR2(20 BYTE) NOT NULL
, OP_DESC NVARCHAR2(20)
, OP_ARGS NVARCHAR2(1000 BYTE)
, STATUS NUMBER(3, 0)
, RESULT VARCHAR2(50 BYTE)
, CONSTRAINT PS_DATA_AUDIT_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PS_DATA_AUDIT_PK ON PS_AUDIT_LOG (ID ASC);
CREATE OR REPLACE PUBLIC SYNONYM PS_AUDIT_LOG FOR PS_AUDIT_LOG;

COMMENT ON TABLE PS_AUDIT_LOG IS '审计数据表';
COMMENT ON COLUMN PS_AUDIT_LOG.OP_USER IS '操作者';
COMMENT ON COLUMN PS_AUDIT_LOG.OP_TYPE IS '操作类型(P=权限管理|A=用户认证|B=业务处理)';
COMMENT ON COLUMN PS_AUDIT_LOG.OP_BEGIN IS '操作开始';
COMMENT ON COLUMN PS_AUDIT_LOG.OP_END IS '操作结束';
COMMENT ON COLUMN PS_AUDIT_LOG.OP_CUA IS '客户端UA';
COMMENT ON COLUMN PS_AUDIT_LOG.OP_CIP IS '客户端IP';
COMMENT ON COLUMN PS_AUDIT_LOG.OP_API IS '操作API';
COMMENT ON COLUMN PS_AUDIT_LOG.OP_DESC IS '操作描述';
COMMENT ON COLUMN PS_AUDIT_LOG.OP_ARGS IS '请求参数';
COMMENT ON COLUMN PS_AUDIT_LOG.STATUS IS '处理结果HTTP状态码';
COMMENT ON COLUMN PS_AUDIT_LOG.RESULT IS '处理结果代码或错误信息';
