-- 在`EDP`中执行以下脚本
-- 外部审计仅保留`MODIFY_TIME`用于数据同步

--------------------
-- 系统用户
--------------------

--DROP SEQUENCE SEQ_PS_AUTH_USER;
CREATE SEQUENCE SEQ_PS_AUTH_USER;
GRANT ALL ON SEQ_PS_AUTH_USER TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_PS_AUTH_USER FOR SEQ_PS_AUTH_USER;

--DROP TABLE PS_AUTH_USER;
CREATE TABLE PS_AUTH_USER
(
  TENANT_ID NUMBER(18, 0) DEFAULT 1 NOT NULL
, ID NUMBER(18, 0) NOT NULL

-- 权限
, LAYER CHAR(1) NOT NULL
, FIELD CHAR(2) NOT NULL

-- 身份: 企业号(ENT_CODE) + 员工号(EMP_CODE)
-- 运营侧: ENT = BP_OU(账户主体所属OU、所以不一定是根OU)
-- 供应商: ENT = BP_SUPP
, ENT_TYPE VARCHAR2(10) DEFAULT 'oper' NOT NULL
, ENT_ID NUMBER(18, 0) NOT NULL
, ENT_CODE NVARCHAR2(40) NOT NULL
, ENT_ADDR NUMBER(18, 0) NOT NULL
, EMP_ID NUMBER(18, 0) DEFAULT 0 NOT NULL
, EMP_CODE NVARCHAR2(40) NOT NULL
, EMP_ADDR NUMBER(18, 0) DEFAULT 0 NOT NULL

-- 凭证
, PASSWORD CHAR(64)
, SALT CHAR(16)

-- 定义
, NAME NVARCHAR2(40) NOT NULL
, EMAIL VARCHAR2(60) NOT NULL
, PHONE VARCHAR2(20) NOT NULL

-- 审计
, CREATE_USER_ID NUMBER(18, 0) NOT NULL
, CREATE_TIME DATE NOT NULL
, MODIFY_USER_ID NUMBER(18, 0) NOT NULL
, MODIFY_TIME DATE NOT NULL
, AUDIT_DATA_VERSION NUMBER(18, 0) NOT NULL
, DELETE_FLAG NUMBER(1, 0) DEFAULT 0 NOT NULL
, CONSTRAINT PS_AUTH_USER_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PS_AUTH_USER_U1 ON PS_AUTH_USER (ENT_CODE, EMP_CODE);
GRANT ALL ON PS_AUTH_USER TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM PS_AUTH_USER FOR PS_AUTH_USER;

COMMENT ON TABLE PS_AUTH_USER IS '系统用户(实施阶段配置平台管理员、运营阶段除了改密码外不可维护)';

COMMENT ON COLUMN PS_AUTH_USER.LAYER IS '用户层级(P:平台级|T:租户级|E:企业级)';
COMMENT ON COLUMN PS_AUTH_USER.FIELD IS '用户领域(PA:平台管理方|TA:租户管理方|EO:企业运营方|EP:企业合作方)';

COMMENT ON COLUMN PS_AUTH_USER.ENT_TYPE IS '企业类型';
COMMENT ON COLUMN PS_AUTH_USER.ENT_ID IS '企业ID';
COMMENT ON COLUMN PS_AUTH_USER.ENT_CODE IS '企业号';
COMMENT ON COLUMN PS_AUTH_USER.ENT_ADDR IS '企业地址号';
COMMENT ON COLUMN PS_AUTH_USER.EMP_ID IS '员工ID';
COMMENT ON COLUMN PS_AUTH_USER.EMP_CODE IS '员工号(即所属企业内用户名)';
COMMENT ON COLUMN PS_AUTH_USER.EMP_ADDR IS '员工地址号';

COMMENT ON COLUMN PS_AUTH_USER.PASSWORD IS '登录密码(SHA256+盐、通过密码找回获得初始密码)';
COMMENT ON COLUMN PS_AUTH_USER.SALT IS '登录密码的盐';

COMMENT ON COLUMN PS_AUTH_USER.NAME IS '名称(用于显示)';
COMMENT ON COLUMN PS_AUTH_USER.PHONE IS '手机';
COMMENT ON COLUMN PS_AUTH_USER.EMAIL IS '邮箱';


--------------------
-- 权限角色
--------------------

--DROP SEQUENCE SEQ_PS_AUTH_ROLE;
CREATE SEQUENCE SEQ_PS_AUTH_ROLE;
GRANT ALL ON SEQ_PS_AUTH_ROLE TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_PS_AUTH_ROLE FOR SEQ_PS_AUTH_ROLE;
--DROP TABLE PS_AUTH_ROLE;
CREATE TABLE PS_AUTH_ROLE
(
  ID NUMBER(18, 0) NOT NULL

-- 维度
, LAYER CHAR(1) NOT NULL
, FIELD CHAR(2) NOT NULL
, TENANT_ID NUMBER(18, 0) DEFAULT 1 NOT NULL

-- 定义
, NAME NVARCHAR2(40) NOT NULL

-- 审计
, MODIFY_TIME DATE DEFAULT SYSDATE NOT NULL
, DELETE_FLAG NUMBER(1, 0) DEFAULT 0 NOT NULL
, CONSTRAINT PS_AUTH_ROLE_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PS_AUTH_ROLE_U1 ON PS_AUTH_ROLE (TENANT_ID, LAYER, NAME);
GRANT ALL ON PS_AUTH_ROLE TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM PS_AUTH_ROLE FOR PS_AUTH_ROLE;

COMMENT ON TABLE PS_AUTH_ROLE IS '权限角色(实施阶段配置、运营阶段亦可维护、外部审计)';
COMMENT ON COLUMN PS_AUTH_ROLE.LAYER IS '用户层级(P:平台级|T:租户级|E:企业级)';
COMMENT ON COLUMN PS_AUTH_ROLE.FIELD IS '用户领域(PA:平台管理方|TA:租户管理方|EO:企业运营方|EP:企业合作方)';
COMMENT ON COLUMN PS_AUTH_ROLE.TENANT_ID IS '租户ID(租户级、企业级有效)';
COMMENT ON COLUMN PS_AUTH_ROLE.NAME IS '名称';


--------------------
-- 权限树
--
-- 1. 设计前需要决策用户权限控制的颗粒度，形成权限配置数据(即权限树深度最小为菜单深度、最大为希望控制的权限深度)。
-- 2. 提供配置画面，配置数据在权限配置画面全部展开，确保父子节点的联动性。
--
--------------------

--DROP TABLE PS_AUTH_PERM;
CREATE TABLE PS_AUTH_PERM
(
-- 层级
  CODE VARCHAR2(20) NOT NULL
, PCODE VARCHAR2(20)
, LVL NUMBER(2, 0) NOT NULL
, SEQ NUMBER(3, 0) NOT NULL

-- 维度
, LAYER CHAR(1) NOT NULL
, FIELD CHAR(1) NOT NULL

-- 定义
, NAME NVARCHAR2(40) NOT NULL
, TYPE CHAR(1) NOT NULL
, APIS VARCHAR2(100) NOT NULL
, MENU_URL VARCHAR2(100)
, MENU_ICO VARCHAR2(20)

-- 时间戳
, MODIFY_TIME DATE DEFAULT SYSDATE NOT NULL
, CONSTRAINT PS_AUTH_PERM_PK PRIMARY KEY (CODE)
);
CREATE UNIQUE INDEX PS_AUTH_PERM_U1 ON PS_AUTH_PERM (LVL, SEQ);
CREATE UNIQUE INDEX PS_AUTH_PERM_U2 ON PS_AUTH_PERM (APIS);
CREATE UNIQUE INDEX PS_AUTH_PERM_U3 ON PS_AUTH_PERM (MENU_URL);
GRANT ALL ON PS_AUTH_PERM TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM PS_AUTH_PERM FOR PS_AUTH_PERM;

COMMENT ON TABLE PS_AUTH_PERM IS '权限树(租户无关、实施阶段配置、运营阶段不可维护';
COMMENT ON COLUMN PS_AUTH_PERM.CODE IS '编码';
COMMENT ON COLUMN PS_AUTH_PERM.PCODE IS '父级权限编码(越往上API匹配范围越大、优先度越低)';
COMMENT ON COLUMN PS_AUTH_PERM.LVL IS '权限层级';
COMMENT ON COLUMN PS_AUTH_PERM.SEQ IS '同级显示顺序';
COMMENT ON COLUMN PS_AUTH_PERM.LAYER IS '用户层级(P:平台级|T:租户级|E:企业级)';
COMMENT ON COLUMN PS_AUTH_PERM.FIELD IS '用户领域(PA:平台管理方|TA:租户管理方|EO:企业运营方|EP:企业合作方)';
COMMENT ON COLUMN PS_AUTH_PERM.NAME IS '名称';
COMMENT ON COLUMN PS_AUTH_PERM.TYPE IS '类别(F:功能项|M:菜单项)';
COMMENT ON COLUMN PS_AUTH_PERM.APIS IS '权限控制的API前缀';
COMMENT ON COLUMN PS_AUTH_PERM.MENU_URL IS '菜单URL(菜单项有效)';
COMMENT ON COLUMN PS_AUTH_PERM.MENU_ICO IS '菜单URL(菜单项有效)';


--------------------
-- 角色赋权
--------------------

--DROP TABLE PS_AUTH_ROLE_PERM;
CREATE TABLE PS_AUTH_ROLE_PERM
(
  ROLE_ID NUMBER(18, 0) NOT NULL
, PERM_CODE VARCHAR2(20) NOT NULL
, TENANT_ID NUMBER(18, 0) DEFAULT 1 NOT NULL

-- 时间戳
, MODIFY_TIME DATE DEFAULT SYSDATE NOT NULL
, CONSTRAINT PS_AUTH_ROLE_PERM_PK PRIMARY KEY (ROLE_ID, PERM_CODE)
);
GRANT ALL ON PS_AUTH_ROLE_PERM TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM PS_AUTH_ROLE_PERM FOR PS_AUTH_ROLE_PERM;

COMMENT ON TABLE PS_AUTH_ROLE_PERM IS '角色赋权(实施阶段配置、运营阶段亦可维护、外部审计)';
COMMENT ON COLUMN PS_AUTH_ROLE_PERM.ROLE_ID IS '权限角色ID';
COMMENT ON COLUMN PS_AUTH_ROLE_PERM.PERM_CODE IS '权限编码';


--------------------
-- 用户角色
--------------------

--DROP TABLE PS_AUTH_USER_ROLE;
CREATE TABLE PS_AUTH_USER_ROLE
(
  USER_ID NUMBER(18, 0) NOT NULL
, ROLE_ID NUMBER(18, 0) NOT NULL
, TENANT_ID NUMBER(18, 0) DEFAULT 1 NOT NULL

-- 时间戳
, MODIFY_TIME DATE DEFAULT SYSDATE NOT NULL
, CONSTRAINT PS_AUTH_USER_ROLE_PK PRIMARY KEY (USER_ID, ROLE_ID)
);
GRANT ALL ON PS_AUTH_USER_ROLE TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM PS_AUTH_USER_ROLE FOR PS_AUTH_USER_ROLE;

COMMENT ON TABLE PS_AUTH_USER_ROLE IS '角色赋权(实施阶段配置、运营阶段亦可维护、外部审计)';
COMMENT ON COLUMN PS_AUTH_USER_ROLE.USER_ID IS '用户ID';
COMMENT ON COLUMN PS_AUTH_USER_ROLE.ROLE_ID IS '权限角色ID';


--------------------
-- UDC
--------------------

CREATE OR REPLACE PUBLIC SYNONYM PB_UDC_TYPE FOR PB_UDC_TYPE;
CREATE OR REPLACE PUBLIC SYNONYM PB_UDC FOR PB_UDC;
