--流程表单配置信息
--DROP TABLE PS_BPM_MODEL;
CREATE TABLE PS_BPM_MODEL
(
  TENANT_ID NUMBER(18) NOT NULL

, PROC_KEY VARCHAR2(64) NOT NULL
, PROC_MODEL CLOB NOT NULL

, CREATE_USER_ID NUMBER(18) DEFAULT 0 NOT NULL
, CREATE_TIME DATE DEFAULT CURRENT_DATE NOT NULL
, MODIFY_USER_ID NUMBER(18) DEFAULT 0 NOT NULL
, MODIFY_TIME DATE DEFAULT CURRENT_DATE NOT NULL
, CONSTRAINT PS_BPM_MODEL_PK PRIMARY KEY (TENANT_ID, PROC_KEY)
);

COMMENT ON TABLE PS_BPM_MODEL IS 'BPM未发布的流程模型';
COMMENT ON COLUMN PS_BPM_MODEL.PROC_KEY IS '流程定义KEY';
COMMENT ON COLUMN PS_BPM_MODEL.PROC_MODEL IS '流程模型(XML)';

GRANT ALL ON PS_BPM_MODEL TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM PS_BPM_MODEL FOR PS_BPM_MODEL;
