--流程表单配置信息
--DROP TABLE PS_BPM_VIEW;
CREATE TABLE PS_BPM_VIEW
(
  TENANT_ID NUMBER(18) NOT NULL

, PROC_DEF_ID VARCHAR2(64) NOT NULL
, TASK_DEF_ID VARCHAR2(255) NOT NULL
, VIEW_MODE VARCHAR2(10) NOT NULL

, VIEW_CONF CLOB NOT NULL

, CREATE_USER_ID NUMBER(18) DEFAULT 0 NOT NULL
, CREATE_TIME DATE DEFAULT CURRENT_DATE NOT NULL
, MODIFY_USER_ID NUMBER(18) DEFAULT 0 NOT NULL
, MODIFY_TIME DATE DEFAULT CURRENT_DATE NOT NULL
, CONSTRAINT PS_BPM_VIEW_PK PRIMARY KEY (TENANT_ID, PROC_DEF_ID, TASK_DEF_ID, VIEW_MODE)
);

COMMENT ON TABLE PS_BPM_VIEW IS 'BPM表单视图配置';
COMMENT ON COLUMN PS_BPM_VIEW.PROC_DEF_ID IS '流程定义ID';
COMMENT ON COLUMN PS_BPM_VIEW.TASK_DEF_ID IS '任务定义ID';
COMMENT ON COLUMN PS_BPM_VIEW.VIEW_MODE IS 'create|edit|view|approval';
COMMENT ON COLUMN PS_BPM_VIEW.VIEW_CONF IS '配置信息(JSON)';

GRANT ALL ON PS_BPM_VIEW TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM PS_BPM_VIEW FOR PS_BPM_VIEW;
