-- 在`EDP`中执行以下脚本

--------------------
-- 流程定义
--------------------

--DROP SEQUENCE SEQ_PS_FLOW_DEF;
CREATE SEQUENCE SEQ_PS_FLOW_DEF;
GRANT ALL ON SEQ_PS_FLOW_DEF TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_PS_FLOW_DEF FOR SEQ_PS_FLOW_DEF;
--DROP TABLE PS_FLOW_DEF;
CREATE TABLE PS_FLOW_DEF
(
  ID NUMBER(18, 0) NOT NULL
, "KEY" NVARCHAR2(64) NOT NULL
, NAME NVARCHAR2(20) NOT NULL
, TENANT_ID NUMBER(18, 0) DEFAULT 1 NOT NULL
, MODIFY_TIME DATE DEFAULT SYSDATE NOT NULL
, CONSTRAINT PS_FLOW_DEF_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PS_FLOW_DEF_PK ON PS_FLOW_DEF (ID ASC);

GRANT ALL ON PS_FLOW_DEF TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM PS_FLOW_DEF FOR PS_FLOW_DEF;

COMMENT ON TABLE PS_FLOW_DEF IS '流程定义';
COMMENT ON COLUMN PS_FLOW_DEF."KEY" IS '流程定义';
COMMENT ON COLUMN PS_FLOW_DEF.NAME IS '流程名称';
COMMENT ON COLUMN PS_FLOW_DEF.TENANT_ID IS '租户(租户级/企业级有效)';


--------------------
-- 流程任务定义
--------------------

--DROP SEQUENCE SEQ_PS_FLOW_TASK;
CREATE SEQUENCE SEQ_PS_FLOW_TASK;
GRANT ALL ON SEQ_PS_FLOW_TASK TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_PS_FLOW_TASK FOR SEQ_PS_FLOW_TASK;
--DROP TABLE PS_FLOW_TASK;
CREATE TABLE PS_FLOW_TASK
(
  ID NUMBER(18, 0) NOT NULL
, DEF_ID NUMBER(18, 0) NOT NULL
, "KEY" NVARCHAR2(64) NOT NULL
, NAME NVARCHAR2(20) NOT NULL
, SETTLED CHAR(1) NOT NULL
, TENANT_ID NUMBER(18, 0) DEFAULT 1 NOT NULL
, MODIFY_TIME DATE DEFAULT SYSDATE NOT NULL
, CONSTRAINT PS_FLOW_TASK_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PS_FLOW_TASK_PK ON PS_FLOW_TASK (ID ASC);
GRANT ALL ON PS_FLOW_TASK TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM PS_FLOW_TASK FOR PS_FLOW_TASK;

COMMENT ON TABLE PS_FLOW_TASK IS '流程任务定义';
COMMENT ON COLUMN PS_FLOW_TASK.DEF_ID IS '流程定义ID';
COMMENT ON COLUMN PS_FLOW_TASK."KEY" IS '任务定义';
COMMENT ON COLUMN PS_FLOW_TASK.NAME IS '任务名称';
COMMENT ON COLUMN PS_FLOW_TASK.TENANT_ID IS '租户(租户级/企业级有效)';
COMMENT ON COLUMN PS_FLOW_TASK.SETTLED IS '是否流程启动时设置任务处理人(Y/N)';


--------------------
-- 流程角色
--------------------

--DROP SEQUENCE SEQ_PS_FLOW_ROLE;
CREATE SEQUENCE SEQ_PS_FLOW_ROLE;
GRANT ALL ON SEQ_PS_FLOW_ROLE TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_PS_FLOW_ROLE FOR SEQ_PS_FLOW_ROLE;
--DROP TABLE PS_FLOW_ROLE;
CREATE TABLE PS_FLOW_ROLE
(
  ID NUMBER(18, 0) NOT NULL

-- 维度
, LAYER CHAR(1) NOT NULL
, FIELD CHAR(2) NOT NULL
, TENANT_ID NUMBER(18, 0) DEFAULT 1 NOT NULL

-- 定义
, NAME NVARCHAR2(40) NOT NULL

-- 审计
, MODIFY_TIME DATE DEFAULT SYSDATE NOT NULL
, DELETE_FLAG NUMBER(1, 0) DEFAULT 0 NOT NULL
, CONSTRAINT PS_FLOW_ROLE_PK PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX PS_FLOW_ROLE_U1 ON PS_FLOW_ROLE (TENANT_ID, LAYER, NAME);
GRANT ALL ON PS_FLOW_ROLE TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM PS_FLOW_ROLE FOR PS_FLOW_ROLE;

COMMENT ON TABLE PS_FLOW_ROLE IS '流程角色';
COMMENT ON COLUMN PS_FLOW_ROLE.LAYER IS '用户层级(P:平台级|T:租户级|E:企业级)';
COMMENT ON COLUMN PS_FLOW_ROLE.FIELD IS '用户领域(PA:平台管理方|TA:租户管理方|EO:企业运营方|EP:企业合作方)';
COMMENT ON COLUMN PS_FLOW_ROLE.TENANT_ID IS '租户ID(租户级、企业级有效)';
COMMENT ON COLUMN PS_FLOW_ROLE.NAME IS '名称';


--------------------
-- 用户流程角色
--------------------

--DROP SEQUENCE SEQ_PS_FLOW_USER_ROLE;
CREATE SEQUENCE SEQ_PS_FLOW_USER_ROLE;
GRANT ALL ON SEQ_PS_FLOW_USER_ROLE TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_PS_FLOW_USER_ROLE FOR SEQ_PS_FLOW_USER_ROLE;
--DROP TABLE PS_FLOW_USER_ROLE;
CREATE TABLE PS_FLOW_USER_ROLE
(
  USER_ID NUMBER(18, 0) NOT NULL
, ROLE_ID NUMBER(18, 0) NOT NULL
, TENANT_ID NUMBER(18, 0) DEFAULT 1 NOT NULL

-- 时间戳
, MODIFY_TIME DATE DEFAULT SYSDATE NOT NULL
, CONSTRAINT PS_FLOW_USER_ROLE_PK PRIMARY KEY (USER_ID, ROLE_ID)
);
GRANT ALL ON PS_FLOW_USER_ROLE TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM PS_FLOW_USER_ROLE FOR PS_FLOW_USER_ROLE;

COMMENT ON TABLE PS_FLOW_USER_ROLE IS '用户流程角色';
COMMENT ON COLUMN PS_FLOW_USER_ROLE.USER_ID IS '用户ID';
COMMENT ON COLUMN PS_FLOW_USER_ROLE.ROLE_ID IS '流程角色ID';
COMMENT ON COLUMN PS_FLOW_USER_ROLE.TENANT_ID IS '租户ID(租户级、企业级有效)';

--------------------
-- 流程角色与任务
--------------------

--DROP SEQUENCE SEQ_PS_FLOW_ROLE_TASK;
CREATE SEQUENCE SEQ_PS_FLOW_ROLE_TASK;
GRANT ALL ON SEQ_PS_FLOW_ROLE_TASK TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_PS_FLOW_ROLE_TASK FOR SEQ_PS_FLOW_ROLE_TASK;
--DROP TABLE PS_FLOW_ROLE_TASK;
CREATE TABLE PS_FLOW_ROLE_TASK
(
  ROLE_ID NUMBER(18, 0) NOT NULL
, TASK_ID NUMBER(18, 0) NOT NULL
, TENANT_ID NUMBER(18, 0) DEFAULT 1 NOT NULL

-- 时间戳
, MODIFY_TIME DATE DEFAULT SYSDATE NOT NULL
, CONSTRAINT PS_FLOW_ROLE_TASK_PK PRIMARY KEY (ROLE_ID, TASK_ID)
);
GRANT ALL ON PS_FLOW_ROLE_TASK TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM PS_FLOW_ROLE_TASK FOR PS_FLOW_ROLE_TASK;

COMMENT ON TABLE PS_FLOW_ROLE_TASK IS '流程角色与任务';
COMMENT ON COLUMN PS_FLOW_ROLE_TASK.ROLE_ID IS '流程角色ID';
COMMENT ON COLUMN PS_FLOW_ROLE_TASK.TASK_ID IS '流程任务ID';
COMMENT ON COLUMN PS_FLOW_ROLE_TASK.TENANT_ID IS '租户ID(租户级、企业级有效)';


--------------------
-- 流程任务历史
--------------------

--DROP SEQUENCE SEQ_PS_FLOW_TRACE;
CREATE SEQUENCE SEQ_PS_FLOW_TRACE;
GRANT ALL ON SEQ_PS_FLOW_TRACE TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_PS_FLOW_TRACE FOR SEQ_PS_FLOW_TRACE;
--DROP TABLE PS_FLOW_TRACE;
CREATE TABLE PS_FLOW_TRACE
(
  ID NUMBER(18, 0) NOT NULL
, PROC_INST_ID NVARCHAR2(64) NOT NULL
, TASK_ID NVARCHAR2(64) NOT NULL
, ASSIGNEE NVARCHAR2(255) NOT NULL
, RESULT NVARCHAR2(20) NOT NULL
, ADVICE NVARCHAR2(500)
, START_TIME DATE DEFAULT SYSDATE NOT NULL
, END_TIME DATE
, TENANT_ID NUMBER(18, 0) DEFAULT 1 NOT NULL

-- 时间戳
, MODIFY_TIME DATE DEFAULT SYSDATE NOT NULL
, CONSTRAINT PS_FLOW_TRACE_PK PRIMARY KEY (ID)
);
GRANT ALL ON PS_FLOW_TRACE TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM PS_FLOW_TRACE FOR PS_FLOW_TRACE;

COMMENT ON TABLE PS_FLOW_TRACE IS '流程任务历史';
COMMENT ON COLUMN PS_FLOW_TRACE.PROC_INST_ID IS '流程实例编号';
COMMENT ON COLUMN PS_FLOW_TRACE.TASK_ID IS '任务ID(运行时)';
COMMENT ON COLUMN PS_FLOW_TRACE.ASSIGNEE IS '处理人';
COMMENT ON COLUMN PS_FLOW_TRACE.RESULT IS '审批结果';
COMMENT ON COLUMN PS_FLOW_TRACE.ADVICE IS '审批意见';
COMMENT ON COLUMN PS_FLOW_TRACE.START_TIME IS '任务开始时间';
COMMENT ON COLUMN PS_FLOW_TRACE.END_TIME IS '任务结束时间';
COMMENT ON COLUMN PS_FLOW_TRACE.TENANT_ID IS '租户ID(租户级、企业级有效)';
