--DROP TABLE PS_GEN_DEF;
CREATE TABLE PS_GEN_DEF
(
  GEN_CODE VARCHAR2(20) NOT NULL
, GEN_NAME NVARCHAR2(40)

, TENANT_ID NUMBER(18) NOT NULL
, APP_CODE VARCHAR2(20) NOT NULL

, SEQ_FMT VARCHAR2(60) NOT NULL
, SEQ_KEY VARCHAR2(60) DEFAULT '-' NOT NULL
, CNT_KEY VARCHAR2(60) DEFAULT '-' NOT NULL
, CNT_LEN NUMBER(2) NOT NULL
, CNT_PAD CHAR(1) DEFAULT '0' NOT NULL
, CNT_MIN NUMBER(18) DEFAULT 1 NOT NULL
, CNT_MAX NUMBER(18) NOT NULL

, MODIFY_TIME DATE DEFAULT CURRENT_DATE NOT NULL
, CONSTRAINT PS_GEN_DEF_PK PRIMARY KEY (GEN_CODE)
);

COMMENT ON TABLE PS_GEN_DEF IS '发号器定义';
COMMENT ON COLUMN PS_GEN_DEF.GEN_CODE IS '发号器代码';
COMMENT ON COLUMN PS_GEN_DEF.GEN_NAME IS '发号器名称';
COMMENT ON COLUMN PS_GEN_DEF.TENANT_ID IS '所属租户ID';
COMMENT ON COLUMN PS_GEN_DEF.APP_CODE IS '所属应用代码';
COMMENT ON COLUMN PS_GEN_DEF.SEQ_FMT IS '流水号模版(printf-style)、含三个%s、分别代表发号键、计数键和计数值';
COMMENT ON COLUMN PS_GEN_DEF.SEQ_KEY IS '发号键模版(SpEL)、变化时新建实例';
COMMENT ON COLUMN PS_GEN_DEF.CNT_KEY IS '计数键模版(SpEL)、变化时重新计数';
COMMENT ON COLUMN PS_GEN_DEF.CNT_LEN IS '计数值长度';
COMMENT ON COLUMN PS_GEN_DEF.CNT_PAD IS '计数值补零';
COMMENT ON COLUMN PS_GEN_DEF.CNT_MIN IS '最小计数值';
COMMENT ON COLUMN PS_GEN_DEF.CNT_MAX IS '最大计数值';

GRANT ALL ON PS_GEN_DEF TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM PS_GEN_DEF FOR PS_GEN_DEF;


--DROP TABLE PS_GEN_SEQ;
CREATE TABLE PS_GEN_SEQ
(
  GEN_CODE VARCHAR2(20) NOT NULL
, SEQ_KEY VARCHAR2(40) DEFAULT '-' NOT NULL
, CNT_KEY VARCHAR2(40) DEFAULT '-' NOT NULL
, CNT_VAL NUMBER(18) NOT NULL
, MODIFY_TIME DATE DEFAULT CURRENT_DATE NOT NULL
, CONSTRAINT PS_GEN_SEQ_PK PRIMARY KEY (GEN_CODE, SEQ_KEY)
);

COMMENT ON TABLE PS_GEN_SEQ IS '发号器实例';
COMMENT ON COLUMN PS_GEN_SEQ.GEN_CODE IS '发号器代码';
COMMENT ON COLUMN PS_GEN_SEQ.SEQ_KEY IS '发号键';
COMMENT ON COLUMN PS_GEN_SEQ.CNT_KEY IS '计数键';
COMMENT ON COLUMN PS_GEN_SEQ.CNT_VAL IS '下一个计数值';

GRANT ALL ON PS_GEN_SEQ TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM PS_GEN_SEQ FOR PS_GEN_SEQ;
