--资料库定义
--DROP TABLE PS_SFS_REPO;
CREATE TABLE PS_SFS_REPO
(
  TENANT_ID NUMBER(18) NOT NULL

, CODE VARCHAR2(20) NOT NULL

, NAME NVARCHAR2(40)
, TYPE CHAR(3) NOT NULL
, EXTS VARCHAR2(100) NULL
, PATH VARCHAR2(250) NULL
, PATH_SYS CHAR(1) DEFAULT 'N' NOT NULL
, PATH_CHK CHAR(1) DEFAULT 'N' NOT NULL
, PATH_WEB VARCHAR2(250) NULL
, SIZE_CHK NUMBER(18) DEFAULT 0 NOT NULL
, QUOTA_MB NUMBER(8) DEFAULT 0 NOT NULL

, CREATE_USER_ID NUMBER(18) DEFAULT 0 NOT NULL
, CREATE_TIME DATE DEFAULT CURRENT_DATE NOT NULL
, MODIFY_USER_ID NUMBER(18) DEFAULT 0 NOT NULL
, MODIFY_TIME DATE DEFAULT CURRENT_DATE NOT NULL
, CONSTRAINT PS_SFS_REPO_PK PRIMARY KEY (TENANT_ID, CODE)
);

COMMENT ON TABLE PS_SFS_REPO IS '资料库定义';
COMMENT ON COLUMN PS_SFS_REPO.CODE IS '资料库代码';
COMMENT ON COLUMN PS_SFS_REPO.NAME IS '资料库名称';
COMMENT ON COLUMN PS_SFS_REPO.TYPE IS 'doc=文档|img=图片|aud=音频|vid=视频';
COMMENT ON COLUMN PS_SFS_REPO.EXTS IS '支持的扩展名列表(逗号分隔)';
COMMENT ON COLUMN PS_SFS_REPO.PATH IS '资料库路径(为空时表示资料存为BLOB、此时建议设置SIZE_CHK检查)';
COMMENT ON COLUMN PS_SFS_REPO.PATH_SYS IS '是否为系统路径(默认为N)';
COMMENT ON COLUMN PS_SFS_REPO.PATH_CHK IS '是否进行路径可用检查(默认为N、表示不存在则创建)';
COMMENT ON COLUMN PS_SFS_REPO.PATH_WEB IS '相应的WEB访问路径';
COMMENT ON COLUMN PS_SFS_REPO.SIZE_CHK IS '是否进行资料大小检查(字节数、默认为0、表示不检查)';
COMMENT ON COLUMN PS_SFS_REPO.QUOTA_MB IS '配额(MB数、默认为0表示额度不限)';

GRANT ALL ON PS_SFS_REPO TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM PS_SFS_REPO FOR PS_SFS_REPO;

--图片的额外检查
--DROP TABLE PS_SFS_IMG_CHECK;
CREATE TABLE PS_SFS_IMG_CHECK
(
  TENANT_ID NUMBER(18) NOT NULL

, REPO_CODE VARCHAR2(20) NOT NULL

, RES_W_MIN NUMBER(8) DEFAULT 0 NOT NULL
, RES_W_MAX NUMBER(8) DEFAULT 0 NOT NULL
, RES_H_MIN NUMBER(8) DEFAULT 0 NOT NULL
, RES_H_MAX NUMBER(8) DEFAULT 0 NOT NULL
, RES_R_MIN_D2 NUMBER(8) DEFAULT 0 NOT NULL
, RES_R_MAX_D2 NUMBER(8) DEFAULT 0 NOT NULL

, CREATE_USER_ID NUMBER(18) DEFAULT 0 NOT NULL
, CREATE_TIME DATE DEFAULT CURRENT_DATE NOT NULL
, MODIFY_USER_ID NUMBER(18) DEFAULT 0 NOT NULL
, MODIFY_TIME DATE DEFAULT CURRENT_DATE NOT NULL
, CONSTRAINT PS_SFS_IMG_CHECK_PK PRIMARY KEY (TENANT_ID, REPO_CODE)
);

COMMENT ON TABLE PS_SFS_IMG_CHECK IS '图片的额外检查';
COMMENT ON COLUMN PS_SFS_IMG_CHECK.REPO_CODE IS '资料库代码';
COMMENT ON COLUMN PS_SFS_IMG_CHECK.RES_W_MIN IS '最小宽度(px、0表示不检查)';
COMMENT ON COLUMN PS_SFS_IMG_CHECK.RES_W_MAX IS '最大宽度(px、0表示不检查)';
COMMENT ON COLUMN PS_SFS_IMG_CHECK.RES_H_MIN IS '最小高度(px、0表示不检查)';
COMMENT ON COLUMN PS_SFS_IMG_CHECK.RES_H_MAX IS '最大高度(px、0表示不检查)';
COMMENT ON COLUMN PS_SFS_IMG_CHECK.RES_R_MIN_D2 IS '最小高宽比(0表示不检查)';
COMMENT ON COLUMN PS_SFS_IMG_CHECK.RES_R_MAX_D2 IS '最大高宽比(0表示不检查)';

GRANT ALL ON PS_SFS_IMG_CHECK TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM PS_SFS_IMG_CHECK FOR PS_SFS_IMG_CHECK;


--图片的缩略处理
--DROP TABLE PS_SFS_IMG_SCALE;
CREATE TABLE PS_SFS_IMG_SCALE
(
  TENANT_ID NUMBER(18) NOT NULL

, REPO_CODE VARCHAR2(20) NOT NULL

, SUFFIX VARCHAR2(10) NOT NULL
, REMARK NVARCHAR2(40)
, RES_W NUMBER(8) NOT NULL
, RES_H NUMBER(8) NOT NULL

, CREATE_USER_ID NUMBER(18) DEFAULT 0 NOT NULL
, CREATE_TIME DATE DEFAULT CURRENT_DATE NOT NULL
, MODIFY_USER_ID NUMBER(18) DEFAULT 0 NOT NULL
, MODIFY_TIME DATE DEFAULT CURRENT_DATE NOT NULL
, CONSTRAINT PS_SFS_IMG_SCALE_PK PRIMARY KEY (TENANT_ID, REPO_CODE, SUFFIX)
);

COMMENT ON TABLE PS_SFS_IMG_SCALE IS '图片的额外检查';
COMMENT ON COLUMN PS_SFS_IMG_SCALE.REPO_CODE IS '资料库代码';
COMMENT ON COLUMN PS_SFS_IMG_SCALE.SUFFIX IS '路径后缀';
COMMENT ON COLUMN PS_SFS_IMG_SCALE.REMARK IS '说明';
COMMENT ON COLUMN PS_SFS_IMG_SCALE.RES_W IS '缩略宽度';
COMMENT ON COLUMN PS_SFS_IMG_SCALE.RES_H IS '缩略高度';

GRANT ALL ON PS_SFS_IMG_SCALE TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM PS_SFS_IMG_SCALE FOR PS_SFS_IMG_CHECK;


--资料项
--DROP TABLE PS_SFS_ITEM;
CREATE TABLE PS_SFS_ITEM
(
  TENANT_ID NUMBER(18) NOT NULL

, REPO_CODE VARCHAR2(20) NOT NULL
, CLS_PATH VARCHAR2(250) NOT NULL
, DATA_KEY VARCHAR2(50) NOT NULL
, TEMP_ITEM CHAR(1) DEFAULT 'N' NOT NULL

, ITEM_HASH CHAR(32) NOT NULL
, ITEM_NAME NVARCHAR2(100) NOT NULL
, ITEM_MIME VARCHAR2(20) NOT NULL
, ITEM_SIZE NUMBER(18) NOT NULL
, ITEM_BLOB BLOB NULL

, CREATE_USER_ID NUMBER(18) DEFAULT 0 NOT NULL
, CREATE_TIME DATE DEFAULT CURRENT_DATE NOT NULL
, MODIFY_USER_ID NUMBER(18) DEFAULT 0 NOT NULL
, MODIFY_TIME DATE DEFAULT CURRENT_DATE NOT NULL
, CONSTRAINT PS_SFS_ITEM_PK PRIMARY KEY (TENANT_ID, REPO_CODE, CLS_PATH, DATA_KEY, ITEM_HASH)
);

COMMENT ON TABLE PS_SFS_ITEM IS '资料项';
COMMENT ON COLUMN PS_SFS_ITEM.REPO_CODE IS '资料库代码';
COMMENT ON COLUMN PS_SFS_ITEM.CLS_PATH IS '资料分类路径';
COMMENT ON COLUMN PS_SFS_ITEM.DATA_KEY IS '所属的数据键(临时资料项时为会话ID)';
COMMENT ON COLUMN PS_SFS_ITEM.TEMP_ITEM IS '是否为临时资料项(Y|N)';
COMMENT ON COLUMN PS_SFS_ITEM.ITEM_HASH IS '资料内容散列(md5)';
COMMENT ON COLUMN PS_SFS_ITEM.ITEM_NAME IS '资料原文件名';
COMMENT ON COLUMN PS_SFS_ITEM.ITEM_MIME IS '资料MIME信息';
COMMENT ON COLUMN PS_SFS_ITEM.ITEM_SIZE IS '资料字节数';

GRANT ALL ON PS_SFS_ITEM TO JMJSRM;
CREATE OR REPLACE PUBLIC SYNONYM PS_SFS_ITEM FOR PS_SFS_ITEM;
